from h2 import *
C="common in DS interviews"
write("algo2", [
Q("algo-013","How does k-means work, how do you choose k, and when does it fail?","ML Algorithms","easy",C,"Phone screen, unsupervised learning",
 [("Why does the result depend on initialization?","test local optima and k-means++"),
  ("What kinds of cluster shapes does it handle poorly?","test non-round shapes, unequal sizes and outliers"),
  ("Do you need to scale the features?","test distance-based methods and scaling")],
 "k-means partitions points by distance to centers, so it assumes roughly round, similar-sized clusters on comparable scales.",
 "It assigns points to the nearest of k centers and then updates the centers.",
 "k-means alternates between assigning each point to its nearest center and moving each center to the mean of its points, until assignments stop changing. It finds a local optimum, so initialization matters; k-means++ and several restarts help. To choose k I'd look at the elbow in within-cluster variance and at silhouette scores, but also at whether the clusters are interpretable and stable across samples. It struggles with elongated or nested shapes, very different cluster sizes and outliers, and it needs scaled numeric features. DBSCAN or Gaussian mixtures are common alternatives.",
 ["clustering"],["k-means","clustering"],"concept"),
Q("algo-014","When would you choose DBSCAN over k-means?","ML Algorithms","medium",C,"Mid-level DS interview, unsupervised learning",
 [("What do eps and min_samples control?","test the density parameters"),
  ("How does DBSCAN treat noise points?","test the noise label"),
  ("When does DBSCAN struggle?","test varying density and high dimensions")],
 "DBSCAN groups by density, so it finds odd shapes and flags noise without being told how many clusters exist, but it assumes one density throughout.",
 "DBSCAN doesn't need k and handles outliers.",
 "DBSCAN grows clusters from dense neighborhoods: a point with at least min_samples neighbors within distance eps is a core point, clusters are connected dense regions, and points in no dense region are labeled noise. I'd choose it over k-means when clusters have irregular shapes, when I don't know k, or when outliers are meaningful. It struggles when clusters differ a lot in density, because one eps cannot suit both, and in high dimensions where distances lose meaning. I'd pick eps from a k-distance plot, and features still need scaling.",
 ["clustering","anomaly-detection"],["dbscan","k-means"],"concept"),
Q("algo-015","What is hierarchical clustering, and when is a dendrogram more useful than k-means?","ML Algorithms","medium",C,"Mid-level DS interview, unsupervised learning",
 [("What is the difference between single, complete and average linkage?","test linkage choice and chaining"),
  ("How do you decide where to cut the tree?","test using merge heights and business needs"),
  ("Why is it hard to run on a million points?","test the pairwise-distance memory cost")],
 "Hierarchical clustering shows how groups merge at every scale, which helps when you don't know how many groups you want or the groups are nested.",
 "It builds a tree of clusters, and you cut it at a level.",
 "Agglomerative clustering starts with each point alone and repeatedly merges the two closest clusters; the dendrogram records every merge and its distance. The linkage rule defines closest: single linkage chains and finds elongated shapes but is noise-sensitive, complete linkage makes compact clusters, and average and Ward sit between. It is useful when the number of groups is unknown or the structure is nested, as with product taxonomies, and I'd pick the cut from large gaps in merge height or from what the business can act on. It needs the pairwise distance matrix, so it is impractical beyond tens of thousands of points without sampling.",
 ["clustering"],["hierarchical-clustering","clustering"],"concept"),
Q("algo-016","How are Gaussian mixture models different from k-means, and what do 'soft assignments' give you?","ML Algorithms","hard",C,"Senior DS interview, unsupervised learning",
 [("How is a mixture model fitted?","test expectation-maximization at a conceptual level"),
  ("What happens if you give the model too many components?","test overfitting and choosing with BIC"),
  ("When would you prefer k-means anyway?","test practicality and speed")],
 "A mixture model gives each point a probability of belonging to each cluster, with clusters of different shapes and sizes, at the cost of more parameters.",
 "A Gaussian mixture gives probabilities instead of hard labels.",
 "k-means is a special case that assumes equal, round clusters and gives hard labels. A Gaussian mixture models the data as a blend of Gaussians, each with its own mean, spread and weight, so clusters can be elliptical and different in size, and each point gets a probability of membership, which is useful for borderline customers or for scoring. It is fitted with expectation-maximization, alternating between computing memberships and updating the Gaussians, and can get stuck in local optima. More components always fit better, so I'd choose the number with BIC or held-out likelihood. k-means is faster and simpler when clusters are roughly round and hard labels are enough.",
 ["clustering","probabilistic-models"],["gaussian-mixture-model","k-means"],"concept"),
Q("algo-017","You clustered customers and there are no labels. How do you tell whether the clusters are any good?","ML Algorithms","hard","common in senior DS interviews","Senior DS interview, unsupervised learning",
 [("What do silhouette scores tell you, and what don't they?","test internal metrics and their bias toward round clusters"),
  ("How would you check stability?","test resampling and re-clustering"),
  ("What is the business test of a segmentation?","test actionability and difference in behavior")],
 "Without labels, good means compact and separated, stable under resampling, and different in ways the business can act on. The first two are measurable; the third is the one that matters.",
 "Use the silhouette score and the elbow method.",
 "I'd check three things. Internal quality: silhouette or Davies-Bouldin say whether clusters are compact and separated, but they reward round clusters and can look fine on arbitrary slices. Stability: re-cluster on bootstrap samples or with different seeds and see whether the same groups reappear; unstable clusters are artifacts. Usefulness: profile each cluster on outcomes not used in the clustering, such as churn or revenue, and ask whether the groups behave differently and whether the team would treat them differently. If I can't describe a cluster in a sentence or act on it, it isn't a segment.",
 ["clustering","validation-strategy","stakeholder-communication"],["clustering"],"case"),
Q("algo-018","Design a customer segmentation for a bank using transaction behavior, demographics and product holdings.","ML Algorithms","medium",C,"DS interview, retail banking",
 [("How do you combine numeric and categorical features?","test Gower distance, encoding and k-prototypes"),
  ("How would you make the segments explainable?","test profiling and a shallow-tree explanation"),
  ("How often should segments be refreshed?","test stability versus drift")],
 "Segmentation succeeds or fails on feature choice and on whether the result is stable and easy to name, not on the algorithm.",
 "Standardize the features and run k-means.",
 "I'd start with the purpose: marketing, risk and service design each want different features. I'd engineer behavioral features (spend mix, balances, tenure, channel use), transform skewed ones, and scale. For mixed numeric and categorical data I'd use Gower distance with hierarchical clustering, k-prototypes, or reduce to embeddings or PCA components first. I'd compare candidate values of k on stability and interpretability, name segments from their profiles, and fit a shallow decision tree on the labels to explain the boundaries. I'd refresh on a schedule and track membership drift so campaigns don't target moving groups.",
 ["clustering","feature-engineering"],["customer-segmentation","clustering"],"case"),
Q("algo-019","What does PCA do, when would you use it, and what do you need to do to the data before running it?","ML Algorithms","medium",C,"Mid-level DS interview",
 [("How do you decide how many components to keep?","test explained variance and scree plots"),
  ("Can you interpret the components?","test loadings and their limits"),
  ("When is PCA a bad idea?","test non-linear structure, tree models and interpretability needs")],
 "PCA rotates the data onto the directions of greatest variance, so it depends on feature scale and compresses linear structure only.",
 "It reduces dimensions by keeping the components with the most variance.",
 "PCA finds orthogonal directions that capture the most variance and projects the data onto the first few. That compresses correlated features, removes noise, and helps visualization or models hurt by collinearity. Because it chases variance, features must be standardized or large-scale features dominate. I'd choose components from cumulative explained variance or a scree plot, or by downstream model performance. Components are linear mixtures, so interpretation relies on loadings and gets hard. It is a poor fit when structure is non-linear, when tree models don't need it, or when you must explain individual features to stakeholders.",
 ["dimensionality-reduction","feature-scaling"],["pca","feature-scaling"],"concept"),
Q("algo-020","A colleague shows a t-SNE plot with clear clusters and says it proves the data has natural groups. How do you respond?","ML Algorithms","hard",C,"Senior DS interview, unsupervised learning",
 [("What do distances between clusters in a t-SNE plot mean?","test that global distances are not meaningful"),
  ("How do perplexity and other settings change the picture?","test sensitivity to parameters"),
  ("How would you check that the clusters are real?","test clustering in the original space and stability")],
 "t-SNE and UMAP preserve local neighborhoods, not global distances or cluster sizes, so a picture of clusters is a hypothesis, not evidence.",
 "t-SNE is only for visualization, so I'd be careful.",
 "I'd say the plot is a good prompt but not proof. t-SNE (and UMAP to a lesser degree) preserves local neighborhoods while distorting global structure, so cluster sizes, the gaps between clusters and their relative positions aren't reliable. The picture also changes with perplexity, initialization and random seed, and can show apparent clusters in structureless noise. To test it I'd re-run with several settings and seeds, cluster in the original or PCA space and compare, check stability under resampling, and see whether the groups differ on outcomes the embedding never saw.",
 ["dimensionality-reduction","clustering","edge-cases"],["t-sne","clustering"],"concept"),
Q("algo-021","You have 2,000 candidate features and 10,000 rows. How do you select features?","ML Algorithms","medium",C,"Mid-level DS interview",
 [("What is the difference between filter, wrapper and embedded methods?","test the taxonomy"),
  ("How can feature selection cause leakage?","test selecting on the full data before cross-validation"),
  ("When would you not bother selecting?","test regularized and boosted models")],
 "Feature selection has to happen inside each cross-validation fold. Otherwise the selection step itself leaks information from the validation data.",
 "Remove low-variance and correlated features, then use importance from a model.",
 "With many more features than the data supports, I'd start with cheap filters: drop constants, near-duplicates and highly correlated pairs, and apply domain judgment. Embedded methods such as lasso or tree-based importance then rank what remains, and wrapper methods such as recursive elimination can refine it at higher cost. The key discipline is doing selection inside each cross-validation fold; selecting on the whole dataset first leaks the labels into the validation score and inflates it. With regularized models or boosting, aggressive selection is often unnecessary, but it can help stability, speed and explainability.",
 ["feature-selection","data-leakage","validation-strategy"],["feature-selection","cross-validation"],"concept"),
Q("algo-022","When does stacking or blending models help, and when is it not worth it?","ML Algorithms","hard",C,"Senior DS interview, applied ML",
 [("Why must the second-level model be trained on out-of-fold predictions?","test leakage in stacking"),
  ("How different do the base models need to be?","test correlation of errors"),
  ("What does it cost in production?","test maintenance and latency")],
 "Ensembling helps when the base models make different mistakes. When they are highly correlated or the system must stay simple, the gain doesn't justify the complexity.",
 "Combining models usually gives better accuracy, as in Kaggle.",
 "Averaging or stacking helps when models make different, partly uncorrelated errors, such as a boosted tree with a linear model or a neural net. Stacking trains a second-level model on the base models' out-of-fold predictions; using in-sample predictions would leak and overstate the benefit. Blending is the simpler version using a holdout set. Gains are typically small on clean tabular data where several boosted models are highly correlated. The costs are real: more training time, latency, monitoring and failure modes. I'd try a simple average first and ship the ensemble only if the gain beats the cost of maintaining it.",
 ["ensembling","model-selection","tradeoffs"],["stacking"],"concept"),
Q("algo-023","Only 2% of your cases are positive. Compare resampling (including SMOTE), class weights and threshold tuning.","ML Algorithms","medium",C,"Mid-level DS interview, imbalanced data",
 [("Why can SMOTE hurt if applied before splitting the data?","test leakage through synthetic samples"),
  ("How does class imbalance change which metric you use?","test precision-recall metrics over accuracy"),
  ("Which approach would you try first, and why?","test preferring simple options")],
 "Imbalance is mostly a metric and threshold problem. Resampling changes what the model sees, so it must happen only inside training folds and often adds little over class weights.",
 "Use SMOTE to balance the classes.",
 "First I'd fix evaluation: accuracy is meaningless at 2%, so I'd use precision-recall, PR AUC and cost-based thresholds. Then compare options on honest folds. Class weights are the simplest: they change the loss without altering the data. Random undersampling is cheap but discards information; oversampling duplicates rows; SMOTE interpolates new minority points and can create unrealistic samples and overlap, and it must be applied only inside the training fold or synthetic points leak into validation. Resampling also distorts predicted probabilities, so I'd recalibrate. I'd try weights plus threshold tuning first and keep resampling only if it measurably helps.",
 ["class-imbalance","evaluation-metrics","data-leakage"],["smote"],"case"),
Q("algo-024","How would you tune hyperparameters, and how do you avoid overfitting to your validation set while doing it?","ML Algorithms","medium",C,"Mid-level DS interview",
 [("Why is random search often better than grid search?","test that only a few hyperparameters matter"),
  ("What does Bayesian optimization do differently?","test sequential, model-based search"),
  ("What is nested cross-validation for?","test an unbiased estimate after tuning")],
 "Every look at the validation score while tuning leaks a little information, so the final estimate needs data the tuning never touched.",
 "Use grid search with cross-validation.",
 "I'd first narrow the space to what matters for the model; for boosting that is learning rate, depth, number of rounds (with early stopping) and regularization. Random search usually beats a grid because only a few hyperparameters really matter and random draws try more distinct values of each; Bayesian optimization (for example Optuna) learns from earlier trials to choose promising ones and is worth it when each run is expensive. Repeated tuning on the same folds overfits them, so I'd keep a final holdout or use nested cross-validation to estimate the tuned procedure's performance, and stop when gains are within noise.",
 ["hyperparameter-tuning","validation-strategy"],["hyperparameter","cross-validation"],"concept"),
])
