from h2 import *
C="common in DS interviews"
write("algo1", [
Q("algo-001","What assumptions does linear regression make, and which ones matter most when you only care about prediction?","ML Algorithms","medium",C,"Mid-level DS interview",
 [("What do you do if the residuals show a pattern?","test diagnosing non-linearity and fixing it with transforms or interactions"),
  ("How do outliers affect it?","test sensitivity of least squares"),
  ("What changes if you care about inference instead of prediction?","test the difference between predictive and inferential needs")],
 "The assumptions matter in proportion to what you use the model for. Prediction mostly needs a roughly linear, stable relationship, while inference also needs well-behaved errors.",
 "Linearity, independence, normal errors and constant variance.",
 "The classic list is a linear relationship, independent errors, constant error variance, roughly normal errors and no severe collinearity. For pure prediction the ones that bite are linearity (a missed curve means systematic error) and independence across train and test (leakage). Constant variance and normality mostly affect confidence and prediction intervals, not point predictions. Outliers can drag least squares, so I'd check leverage and consider a robust or Huber loss. I'd diagnose with residual plots and fix with transforms, interaction terms or a more flexible model.",
 ["linear-models","debugging"],["linear-regression","residual"],"concept"),
Q("algo-002","When would you choose ridge, lasso or elastic net?","ML Algorithms","medium",C,"Mid-level DS interview",
 [("Why does lasso set some coefficients exactly to zero while ridge does not?","test geometric intuition for L1 versus L2"),
  ("What happens with a group of highly correlated features?","test lasso instability and elastic net grouping"),
  ("How do you choose the penalty strength?","test cross-validating the penalty and scaling features first")],
 "Ridge shrinks every coefficient, lasso also selects features, and elastic net keeps lasso's selection while behaving better with correlated features.",
 "Lasso removes features and ridge shrinks them.",
 "All three add a penalty to reduce variance. Ridge (L2) shrinks coefficients smoothly and keeps every feature, which suits many features that each carry a little signal. Lasso (L1) can set coefficients exactly to zero, so it selects features, which suits sparse problems and interpretability. With correlated features lasso tends to pick one arbitrarily and flip between samples, while elastic net mixes both penalties and tends to keep correlated groups together. I standardize features first, choose the penalty strength by cross-validation, and use time-aware folds for time-ordered data.",
 ["linear-models","bias-variance","model-selection"],["ridge","lasso"],"concept"),
Q("algo-003","How does a decision tree choose where to split, and why do deep trees overfit?","ML Algorithms","easy",C,"Phone screen, ML fundamentals",
 [("What is impurity and how is it measured?","test knowing Gini and entropy"),
  ("How can you stop a tree from overfitting?","test depth limits, minimum leaf size and pruning"),
  ("Can a tree predict beyond the range of its training data?","test that trees predict piecewise constants")],
 "A tree greedily picks the split that most reduces impurity, and with no limits it keeps splitting until it memorizes the training data.",
 "It picks the best feature to split on, and deep trees memorize the data.",
 "At each node the tree tries candidate splits on each feature and picks the one that most reduces impurity (Gini or entropy for classification, variance for regression). That is greedy: it does not look ahead. Left unchecked it splits until leaves are nearly pure, so it fits noise and generalizes poorly. Remedies are limiting depth, requiring a minimum number of samples per leaf, pruning, or using an ensemble. A tree predicts piecewise constants, so it cannot extrapolate beyond the training range, which matters for trends.",
 ["decision-trees","bias-variance"],["decision-tree"],"concept"),
Q("algo-004","How does a random forest differ from a single tree, and what can go wrong when you read its feature importances?","ML Algorithms","medium",C,"Mid-level DS interview",
 [("What is out-of-bag error?","test knowing it is a built-in validation estimate"),
  ("Why are impurity-based importances biased toward some features?","test the bias toward high-cardinality and continuous features"),
  ("What would you use instead?","test permutation importance and SHAP")],
 "A forest cuts variance by averaging many decorrelated trees, but its default importances favor features with many possible splits and divide credit between correlated features.",
 "A forest averages many trees, and importance shows which features matter.",
 "Each tree trains on a bootstrap sample and considers a random subset of features at each split, so the trees are decorrelated and averaging them reduces variance without raising bias much. Out-of-bag samples give a built-in validation estimate. Default impurity-based importances are biased toward continuous or high-cardinality features and are computed on training data, so they can reward overfit features; correlated features also split the credit. I'd use permutation importance on held-out data or SHAP, and describe the result as what the model uses, not what causes the outcome.",
 ["decision-trees","explainability"],["random-forest","feature-importance"],"concept"),
Q("algo-005","You're choosing between XGBoost, LightGBM and CatBoost for a tabular problem with many categorical features. How do you decide?","ML Algorithms","medium",C,"Mid-level DS interview, tabular ML",
 [("How do their tree-growing strategies differ?","test level-wise versus leaf-wise growth"),
  ("How does each handle categorical variables?","test native categorical handling"),
  ("How would you compare them fairly?","test same folds, same tuning budget, and measuring time as well as accuracy")],
 "On most tabular data the three land within noise of each other. The choice comes down to categorical handling, speed at your data size and how much tuning you can afford.",
 "XGBoost is the standard, LightGBM is faster and CatBoost handles categories.",
 "All three are gradient-boosted trees, and with equal tuning they are usually within a small margin on accuracy, so I'd decide on practical grounds. LightGBM grows trees leaf-wise with histogram binning, which is fast on large data but can overfit small data without limits on leaves. XGBoost is the most widely deployed and documented, with level-wise growth by default. CatBoost uses ordered target statistics to handle categorical features natively and reduce target leakage, often needing less tuning. With many categoricals I'd start with CatBoost, then compare all three on the same time-aware folds with a fixed tuning budget, looking at accuracy, training time and calibration.",
 ["gradient-boosting","model-selection","tradeoffs"],["xgboost","lightgbm","catboost"],"case"),
Q("algo-006","Explain how a support vector machine works. When would you use one, and what do you need to do to the data first?","ML Algorithms","medium",C,"Mid-level DS interview, classical ML",
 [("What does the kernel trick do?","test intuition for non-linear boundaries"),
  ("What do C and gamma control?","test the margin-versus-errors trade-off and kernel width"),
  ("Why does an SVM scale poorly to millions of rows?","test training cost growing faster than linearly with rows")],
 "An SVM finds the boundary with the widest margin, and because margins depend on distances, features must be scaled.",
 "It draws a line between the classes with the biggest gap.",
 "An SVM finds the separating boundary with the largest margin between classes; only the points nearest the boundary, the support vectors, define it. A kernel such as the RBF lets it draw non-linear boundaries by implicitly mapping the data to a higher dimension. C trades margin width against misclassified training points, and gamma sets how local the RBF kernel is. Distances drive everything, so features must be standardized. It works well on small to medium, high-dimensional data like text, but training scales roughly quadratically or worse with rows and its scores are not probabilities, so for large tabular data I'd pick boosting.",
 ["svm","model-selection"],["support-vector-machine"],"concept"),
Q("algo-007","How does support vector regression differ from ordinary linear regression, and when might you prefer it?","ML Algorithms","hard",C,"Senior DS interview, classical ML",
 [("What is the epsilon-insensitive loss?","test the idea of a tolerance tube"),
  ("What happens to points inside the tube?","test sparsity of support vectors"),
  ("How does it compare with ridge for a typical tabular problem?","test pragmatic judgment")],
 "SVR ignores errors smaller than a tolerance, so only points outside it shape the model. That makes it robust to small noise, but it is not automatically better than a regularized linear model.",
 "SVR uses support vectors and kernels to fit a curve instead of a line.",
 "Linear regression minimizes squared error on every point. SVR defines a tube of width epsilon around the fit: errors inside the tube cost nothing and errors outside are penalized linearly, with C controlling how heavily. Only points on or outside the tube become support vectors, so the model is sparse and less sensitive to small noise or moderate outliers, and a kernel gives non-linear fits. It needs scaled features and tuning of epsilon, C and gamma. For ordinary tabular regression a regularized linear model or boosting is usually simpler and as good; I'd reach for SVR on smaller, smooth, non-linear problems.",
 ["svm","linear-models"],["support-vector-regression"],"concept"),
Q("algo-008","How does k-nearest neighbors work, and what are its weaknesses?","ML Algorithms","easy",C,"Phone screen, ML fundamentals",
 [("How do you choose k?","test the bias-variance trade-off and cross-validation"),
  ("Why does it struggle in high dimensions?","test the curse of dimensionality"),
  ("Why must features be scaled?","test distances being dominated by large-valued features")],
 "k-NN has no training step. All of its cost and all of its assumptions sit in the distance function, which breaks down when features are unscaled or numerous.",
 "It looks at the k closest points and takes a vote.",
 "k-NN stores the training data and predicts by taking the majority label (or the average) of the k closest points under a distance metric. Small k gives a jagged, high-variance boundary and large k smooths toward the base rate, so I choose k by cross-validation. Because it uses distance, features must be scaled and irrelevant ones removed; in high dimensions distances become nearly equal, so neighbors stop being meaningful. Prediction is slow on large data without an index or approximate search. It is a useful baseline and underlies many retrieval systems.",
 ["knn","bias-variance"],["k-nearest-neighbors"],"concept"),
Q("algo-009","Naive Bayes assumes features are independent, which is almost never true. Why does it still work, and when would you use it?","ML Algorithms","easy",C,"Phone screen, ML fundamentals",
 [("Where does it fail?","test double-counting of correlated features and poor probabilities"),
  ("What is smoothing for?","test the zero-count problem"),
  ("How does it handle text?","test the bag-of-words setup")],
 "Naive Bayes only needs the right class to score highest, not accurate probabilities, so its wrong independence assumption often hurts less than expected.",
 "It's fast and works well for text even though the assumption is wrong.",
 "It multiplies per-feature likelihoods as if features were independent given the class. The assumption is wrong, but classification only needs the correct class to come out on top, and errors from double-counting correlated features often don't change that ordering. Its probabilities are badly calibrated, so I wouldn't use them for cost-based decisions without recalibration. It trains in one pass, needs little data and handles high-dimensional sparse features like words, which is why it is a strong text baseline. Smoothing prevents a single unseen word from zeroing out a class.",
 ["probabilistic-models","model-selection"],["naive-bayes"],"concept"),
Q("algo-010","You fit a logistic regression for loan default. How do you interpret the coefficients, and why might you still choose it over a boosted model?","ML Algorithms","easy",C,"Mid-level DS interview, lending",
 [("What does a coefficient of 0.7 mean?","test log-odds and odds-ratio interpretation"),
  ("What do you need to check about the features?","test scaling, collinearity and linearity in the log-odds"),
  ("How do you capture non-linear effects?","test binning, splines and interactions")],
 "Each coefficient is a change in log-odds with the other features held fixed, and that transparency is often worth a small loss in accuracy.",
 "Positive coefficients increase the chance of default, and it's simple and explainable.",
 "A coefficient is the change in log-odds of default for a one-unit increase in a feature with the others held fixed; exponentiating gives an odds ratio, so 0.7 means about twice the odds. That reading is only safe if features are on comparable scales and not strongly collinear. I'd check linearity in the log-odds and add splines, bins or interactions where needed. I'd keep it over boosting when regulators or stakeholders need clear reasons, when data is small, or when the accuracy gap is within noise, and I'd verify that with a held-out comparison and a calibration check instead of assuming.",
 ["linear-models","explainability","model-selection"],["logistic-regression","default-rate"],"concept"),
Q("algo-011","You have millions of transactions and almost no labeled fraud. How would you use an unsupervised approach, such as an isolation forest, to find suspicious ones?","ML Algorithms","medium",C,"Senior DS interview, fraud or risk",
 [("How does an isolation forest decide a point is unusual?","test the random-partitioning intuition"),
  ("How do you set the alert threshold without labels?","test tying it to review capacity and sampling for precision"),
  ("How do you know it finds fraud and not just unusual-but-fine transactions?","test validation with analysts")],
 "Unsupervised detectors rank what is unusual, not what is fraudulent, so their value depends on analyst feedback and a threshold tied to review capacity.",
 "Use an isolation forest to flag outliers and review them.",
 "An isolation forest builds random trees that split features at random; points that are isolated in few splits are unusual, so a shorter average path length means a higher anomaly score. I'd engineer behavioral features (amount versus the customer's norm, velocity, new merchant), since raw amounts mostly flag rich customers. With no labels the threshold comes from review capacity: flag the top N per day. Unusual is not the same as fraudulent, so I'd have analysts label a sample from the top of the ranking, measure precision, and feed the labels into a supervised model over time. Segmenting by customer type improves it.",
 ["anomaly-detection","fraud-detection","edge-cases"],["isolation-forest","anomaly-detection"],"case"),
Q("algo-012","You need to model the number of insurance claims per customer per year. Why not just use linear regression, and what would you use?","ML Algorithms","hard","common in senior DS interviews","Senior DS interview, insurance or risk",
 [("What distribution suits count data?","test Poisson and overdispersion"),
  ("What do you do when the variance is much larger than the mean?","test negative binomial and zero inflation"),
  ("How do you handle customers observed for different lengths of time?","test exposure offsets")],
 "Counts are non-negative integers whose variance grows with the mean, so a model built for counts, with an exposure term, beats a straight line.",
 "Use Poisson regression because it's count data.",
 "Linear regression can predict negative claims and assumes constant variance, but counts are non-negative integers whose variance rises with the mean. A generalized linear model with a log link and a Poisson distribution fits that shape, and coefficients become multiplicative effects on the claim rate. Real claims are often overdispersed (variance above the mean), so I'd check that and move to a negative binomial, or add a zero-inflation component when many customers have none. Customers observed for different periods need an exposure offset so the model predicts a rate. Gradient boosting with a Poisson objective is a flexible alternative.",
 ["probabilistic-models","model-selection","edge-cases"],["generalized-linear-model"],"case"),
])
