from h2 import *
C="common in DS interviews"
I="increasingly common"
write("dl", [
Q("dl-001","Explain how a neural network learns, in terms a non-technical colleague would follow.","Deep Learning & NLP","easy",C,"Phone screen, stakeholder communication",
 [("What does backpropagation actually compute?","test the chain rule and gradients"),
  ("Why do we need non-linear activation functions?","test that stacked linear layers collapse into one"),
  ("What can go wrong during training?","test vanishing gradients, divergence and overfitting")],
 "A network adjusts millions of weights a little at a time in the direction that reduces its error. Backpropagation is the efficient way to find that direction.",
 "It has layers of neurons and learns weights through backpropagation.",
 "A network is a stack of simple functions: each layer multiplies inputs by weights and applies a non-linear activation. Training starts with random weights, makes predictions, measures the error with a loss, then uses backpropagation, the chain rule applied layer by layer, to compute how much each weight contributed to the error. Gradient descent nudges every weight slightly to reduce it, and this repeats over many batches. Without the non-linearities the layers would collapse into one linear model. Typical problems are overfitting, unstable learning rates and vanishing gradients, handled with regularization, tuning and normalization.",
 ["neural-networks","explaining-concepts"],["neural-network","backpropagation"],"concept"),
Q("dl-002","What is the difference between gradient descent, SGD and Adam? How does the learning rate affect training?","Deep Learning & NLP","medium",C,"Mid-level DS interview, deep learning",
 [("What do you see in the loss curve if the learning rate is too high or too low?","test diagnosing from curves"),
  ("Why use mini-batches?","test the noise versus compute trade-off"),
  ("Why might you still use SGD with momentum?","test generalization claims")],
 "All three step downhill on the loss. They differ in how much data each step uses and how they adapt the step size, and the learning rate is the most important setting of all.",
 "Adam is an adaptive version of gradient descent.",
 "Gradient descent moves the weights against the gradient of the loss computed on all the data; SGD uses one example or a mini-batch, which is far cheaper per step and adds noise that can help escape poor spots. Momentum smooths the steps. Adam keeps running averages of the gradient and its square and gives each weight its own effective step size, so it usually converges fast with little tuning. The learning rate matters most: too high and the loss oscillates or diverges, too low and it crawls or stalls. I'd use a warmup and decay schedule, watch loss curves, and note that well-tuned SGD with momentum sometimes generalizes slightly better.",
 ["optimization","neural-networks"],["gradient-descent","learning-rate"],"concept"),
Q("dl-003","How do you choose a loss function? Compare MSE, MAE, Huber and cross-entropy.","Deep Learning & NLP","medium",C,"Mid-level DS interview",
 [("What does squared error assume about outliers?","test sensitivity to large errors"),
  ("Why train with cross-entropy instead of accuracy?","test differentiability and probability outputs"),
  ("When would you design a custom loss?","test aligning the loss with business costs")],
 "The loss is the definition of wrong that the model optimizes, so it should match the cost of errors in the real decision.",
 "MSE for regression and cross-entropy for classification.",
 "The loss encodes what counts as an error. MSE penalizes large errors quadratically, so it targets the mean and is sensitive to outliers; MAE targets the median and is robust but has a constant gradient; Huber is quadratic for small errors and linear for large ones, a compromise. Cross-entropy (log loss) trains classifiers to output well-behaved probabilities and is smooth, unlike accuracy, which has no usable gradient. When errors have asymmetric business costs, such as under-forecasting being worse than over-forecasting, I'd use a quantile or custom weighted loss, and still evaluate with the metric the business uses.",
 ["loss-functions","model-selection","cost-sensitive-decisions"],["loss-function"],"concept"),
Q("dl-004","Your neural network overfits. What are your options, and how do dropout and batch normalization differ?","Deep Learning & NLP","medium",C,"Mid-level DS interview, deep learning",
 [("What does early stopping do?","test using validation loss to stop training"),
  ("Why does data augmentation help?","test regularization through data"),
  ("Is batch normalization a regularizer?","test knowing its main purpose")],
 "Dropout and batch normalization solve different problems. Dropout fights overfitting by injecting noise, while batch normalization mainly stabilizes and speeds up training.",
 "Add dropout and use early stopping.",
 "Options in rough order of effort: get more or augmented data, simplify the architecture, add weight decay, use early stopping on validation loss, and add dropout. Dropout randomly zeroes units during training so the network can't rely on any single path, which acts like averaging many sub-networks. Batch normalization standardizes layer inputs within each batch, which stabilizes gradients and allows higher learning rates; it has a mild regularizing side effect but is mainly an optimization aid. I'd first diagnose with train versus validation curves to be sure it is overfitting and not a leak or a bug.",
 ["neural-networks","bias-variance"],["dropout","batch-normalization"],"concept"),
Q("dl-005","Your team wants a deep neural network for a tabular credit-risk dataset with 200,000 rows. Do you agree?","Deep Learning & NLP","hard","common in senior DS interviews","Senior DS interview, applied ML",
 [("Why do tree ensembles often win on tabular data?","test inductive bias and heterogeneous features"),
  ("When would a neural network make sense?","test large data, embeddings, multi-task and multimodal cases"),
  ("How would you run a fair comparison?","test baselines and equal tuning effort")],
 "On tabular data of this size, gradient boosting is usually the stronger and cheaper baseline. A neural network has to earn its place with a specific advantage.",
 "Neural networks are more powerful, so try one.",
 "I'd start with a boosted-tree baseline: on mid-sized tabular data it usually matches or beats deep models, trains in minutes, handles mixed types and missing values, and is easier to explain and monitor. Tabular features are heterogeneous and often have sharp thresholds that trees capture well, while neural networks need careful scaling, encoding and tuning. A network earns its place with a specific advantage: very large data, learned embeddings for high-cardinality categories, multi-task or multimodal inputs, or online updates. I'd compare both on the same time-aware folds with comparable tuning effort, including calibration, latency and maintenance cost, and decide on the whole picture.",
 ["neural-networks","model-selection","tradeoffs"],["neural-network","gradient-boosting"],"case"),
Q("dl-006","What is a convolutional neural network, and why does it work for images?","Deep Learning & NLP","easy",C,"Phone screen, deep learning",
 [("What does a convolution filter do?","test local pattern detection"),
  ("Why is weight sharing important?","test parameter efficiency and translation tolerance"),
  ("When could you use a CNN on something that isn't an image?","test audio, time series and text uses")],
 "A CNN reuses small filters across the whole image, so it detects a pattern wherever it appears with far fewer parameters than a fully connected network.",
 "CNNs use filters to detect features like edges.",
 "A convolutional layer slides a small filter over the input and records how strongly each location matches a pattern, such as an edge. Early layers detect simple patterns and deeper layers combine them into shapes and objects. Because the same filter is reused everywhere, the network needs far fewer parameters than a fully connected one and recognizes a pattern regardless of where it appears. Pooling summarizes regions and adds some tolerance to small shifts. The same idea works for any grid-like data with local structure, including audio spectrograms and some time series, although for most new work a pretrained model is the starting point.",
 ["neural-networks"],["convolutional-neural-network"],"concept"),
Q("dl-007","Why did transformers largely replace RNNs and LSTMs for language tasks?","Deep Learning & NLP","medium",C,"Mid-level DS interview, NLP",
 [("What problem do LSTMs have with long sequences?","test vanishing gradients and limited memory"),
  ("What is the cost of attention?","test quadratic cost in sequence length"),
  ("When might you still use an RNN?","test streaming and small-footprint cases")],
 "Transformers process all tokens at once and let any token look directly at any other, which trains faster on modern hardware and handles long-range dependencies better.",
 "Transformers use attention and can be parallelized.",
 "RNNs and LSTMs read a sequence one step at a time, passing a hidden state forward. That is inherently sequential, so training can't be parallelized across positions, and information from early tokens has to survive many steps, which makes long-range dependencies hard. Transformers use attention so every token can directly weigh every other token, and all positions are processed in parallel, which maps well onto GPUs and scales with data and size. The cost is attention that grows quadratically with sequence length, which drives work on efficient variants and long-context methods. RNN-style models are still used for streaming or very small-footprint settings.",
 ["sequence-models"],["rnn","transformer"],"concept"),
Q("dl-008","Explain attention to a colleague who has never studied deep learning.","Deep Learning & NLP","hard",I,"Senior DS interview, explaining concepts",
 [("What are queries, keys and values?","test the roles of the three"),
  ("Why divide by the square root of the dimension?","test scaling for a stable softmax"),
  ("What is multi-head attention for?","test tracking several relationships at once")],
 "Attention lets each word decide how much to read from every other word, using a learned relevance score, and then blends their information accordingly.",
 "Attention lets the model focus on the important words.",
 "For each word, the model asks a question (the query) and compares it against a label (the key) on every other word; a high match means this word is relevant to me. Those match scores are turned into weights that sum to one, and the word's new representation is a weighted blend of the other words' content (their values). So in 'the animal didn't cross the street because it was tired', the representation of 'it' can pull in information from 'animal'. Scores are scaled so the softmax stays well behaved, and multiple heads let the model track different relationships, such as syntax and reference, at the same time.",
 ["sequence-models","explaining-concepts"],["attention","transformer"],"concept"),
Q("dl-009","You have 500 labeled images and need a classifier. How would you approach it?","Deep Learning & NLP","medium",C,"Mid-level DS interview, applied deep learning",
 [("What does it mean to fine-tune only the last layers?","test freezing and adapting a pretrained model"),
  ("How do you stop it overfitting with so little data?","test augmentation, regularization and a small learning rate"),
  ("How would you know the pretrained features suit your domain?","test domain shift and evaluation")],
 "With little labeled data, start from a model pretrained on a large dataset and adapt it, instead of training from scratch.",
 "Use transfer learning with a pretrained model like ResNet.",
 "Training from scratch on 500 images would overfit, so I'd start from a model pretrained on a large dataset such as ImageNet, whose early layers already detect general patterns. First I'd freeze the backbone and train a new classification head, which is cheap and hard to overfit, then optionally unfreeze the top layers with a small learning rate. Augmentation (crops, flips, color jitter) and early stopping help, and I'd use stratified cross-validation since a single validation split of 100 images is noisy. If the domain is very different, such as medical scans, generic features may transfer less well, so I'd check against a baseline and consider a domain-specific pretrained model.",
 ["transfer-learning","neural-networks","edge-cases"],["pretrained-model"],"case"),
Q("dl-010","You need to classify support tickets by topic. Would you start with TF-IDF and logistic regression, or with embeddings or an LLM?","Deep Learning & NLP","medium",I,"Mid-level DS interview, NLP",
 [("What does TF-IDF capture and miss?","test word weighting without meaning"),
  ("When would embeddings beat TF-IDF?","test synonyms and short texts"),
  ("How would you decide between the options?","test baseline, cost, latency and labeled data")],
 "Start with the cheapest strong baseline and let the data show whether the added cost of embeddings or an LLM buys real accuracy.",
 "Use an LLM because it's the most accurate.",
 "I'd start with TF-IDF and logistic regression: it trains in seconds, needs little data, is easy to debug and often performs well when topics are signalled by distinctive words. TF-IDF weights words by how specific they are to a document but has no notion of meaning, so synonyms and paraphrases look unrelated. Embeddings from a pretrained model capture meaning and help on short or varied text, and they can feed the same simple classifier. An LLM can classify with few or no labels, at higher cost, latency and variability. I'd compare on one labeled test set for accuracy, cost per ticket and latency, and choose the simplest option that meets the target.",
 ["text-features","model-selection","tradeoffs"],["tf-idf","embedding","logistic-regression"],"case"),
Q("dl-011","How are word embeddings like word2vec learned, and what are their limits?","Deep Learning & NLP","medium",C,"Mid-level DS interview, NLP",
 [("Why do similar words end up close together?","test the distributional idea"),
  ("What happens to words with several meanings?","test polysemy"),
  ("How do contextual embeddings differ?","test BERT-style context")],
 "Words that appear in similar contexts get similar vectors, but a single vector per word cannot represent different meanings of the same word.",
 "They turn words into vectors so similar words are close together.",
 "word2vec trains a small network on a prediction task: given a word, predict its neighbors (skip-gram), or the reverse. The vectors that make that prediction work well end up placing words used in similar contexts near each other, following the idea that a word is defined by the company it keeps. Limits: each word has one vector regardless of sense, so 'bank' for rivers and 'bank' for money are blended; rare words get poor vectors; and embeddings absorb biases in the training text. Contextual embeddings from transformer models produce a different vector for each occurrence, which fixes much of the ambiguity problem.",
 ["text-features","embeddings-and-search"],["word2vec","embedding"],"concept"),
Q("dl-012","At a high level, how is a chat model like ChatGPT trained after pretraining? What does RLHF add?","Deep Learning & NLP","hard",I,"Senior DS interview, LLM fundamentals",
 [("What is the difference between pretraining and instruction tuning?","test knowing the stages"),
  ("What is a reward model?","test preference data and learned rewards"),
  ("What are the risks of optimizing against a reward model?","test reward hacking and sycophancy")],
 "Pretraining teaches language, instruction tuning teaches the format of helpful answers, and RLHF steers behavior toward what people prefer, at the risk of optimizing the proxy instead of the goal.",
 "It's trained with human feedback to be more helpful.",
 "Stage one is pretraining on a huge text corpus to predict the next token, which gives broad knowledge but not good behavior. Stage two is supervised instruction tuning on examples of good responses so the model follows prompts. Stage three, RLHF, collects human comparisons between model answers, trains a reward model to predict which is preferred, and then optimizes the chat model against that reward with reinforcement learning while keeping it close to the original. The risk is that the reward model is only a proxy: models can learn to please raters, becoming sycophantic or verbose, which is why evaluation, diverse rater guidelines and newer preference-optimization methods matter.",
 ["llm-training","llm-fundamentals"],["rlhf"],"concept"),
])
