from h import *
C="common in DS interviews"
write("ml", [
Q("ml-011","Your model has 99% training accuracy and 71% validation accuracy. What's going on, and what do you try?","ML","easy",C,"Phone screen, ML fundamentals",
 [("How would you tell whether more data would help?","test learning curves"),
  ("Which levers reduce the gap, and which do you try first?","test prioritizing regularization, simpler models, features and data"),
  ("Could the validation set itself be the problem?","test suspicion of the split")],
 "A large train-validation gap points to high variance, but check that the split is trustworthy before reaching for a fix.",
 "It's overfitting, so add regularization or dropout.",
 "That gap suggests the model has memorized training patterns that don't generalize, meaning high variance. Before changing the model I'd confirm the split is valid: no duplicates across sets, similar distributions, no leakage. Then I'd plot learning curves: if validation error keeps falling with more data, collecting more helps; if it plateaus, reduce complexity. I'd try, roughly in this order: a simpler model or stronger regularization, early stopping, feature pruning, more or augmented data, and cross-validation for a steadier estimate. Each change is judged on the validation gap and the validation score together.",
 ["bias-variance","validation-strategy","debugging"],["accuracy","validation-set"],"case"),
Q("ml-012","Explain the difference between bagging and boosting. Why does a random forest tolerate deep trees while boosting usually uses shallow ones?","ML","easy",C,"Phone screen, ML fundamentals",
 [("Which of the two is more sensitive to noisy labels?","test boosting chasing noise"),
  ("When would you choose a random forest over XGBoost?","test practical model selection"),
  ("What does the learning rate do in boosting?","test shrinkage and its trade-off with the number of rounds")],
 "Bagging averages many independent high-variance models to cut variance. Boosting adds weak models in sequence to cut bias.",
 "Bagging trains models in parallel and boosting trains them one after another.",
 "Bagging, as in a random forest, trains many deep, high-variance trees independently on bootstrap samples and averages them. Averaging cancels much of the variance, so the individual trees can be deep. Boosting builds trees sequentially, each fitting the errors of the ensemble so far, which reduces bias, so each tree can be shallow and weak; the learning rate scales how much each one contributes. Boosting usually reaches higher accuracy on tabular data but is more sensitive to noisy labels and needs more tuning. A random forest is a robust, low-tuning baseline that is hard to overfit badly. I'd start with a forest and move to XGBoost when accuracy matters.",
 ["gradient-boosting","model-selection","explaining-concepts"],["random-forest","gradient-boosting"],"concept"),
Q("ml-013","Your classifier has 0.92 AUC, but cases it scores at 0.8 are positive only 50% of the time. Does that matter?","ML","medium",C,"Mid-level DS interview",
 [("When does ranking quality alone suffice, and when does the probability itself matter?","test linking the metric to the decision"),
  ("How would you detect and fix this?","test reliability plots, Platt scaling and isotonic regression"),
  ("Which model types tend to have this problem?","test knowledge across model families")],
 "AUC measures ranking. If anyone multiplies the score by a cost or reports it as a probability, whether it is trustworthy decides the outcome.",
 "AUC is high, so the model is good.",
 "It depends on how the score is used. If we only rank cases and take the top K, AUC is what matters. If we use the output as a probability, for expected loss, pricing or cost-based thresholds, a score of 0.8 that really means 50% leads to wrong decisions. I'd check with a reliability diagram and the Brier score, then recalibrate on a held-out set with Platt scaling or isotonic regression, which leaves AUC roughly unchanged. Boosted trees and naive Bayes often need it; logistic regression is usually better behaved. Calibration also drifts when class balance shifts, so I'd monitor it.",
 ["calibration","evaluation-metrics","tradeoffs"],["auc","predicted-probability"],"concept"),
Q("ml-014","A feature has 50,000 distinct values, such as merchant ID or zip code. How do you use it in a model?","ML","medium",C,"Mid-level DS interview",
 [("What goes wrong with one-hot encoding here?","test dimensionality and sparsity"),
  ("How do you avoid leaking the target when you encode with target statistics?","test out-of-fold encoding"),
  ("What do you do with values never seen in training?","test handling unseen categories")],
 "Encoding a high-cardinality feature is easy. Encoding it without leaking the target and with a plan for new values is the hard part.",
 "One-hot encode it.",
 "One-hot would create 50,000 sparse columns, slow training and overfit rare values. Options: frequency or count encoding; target encoding computed out of fold with smoothing toward the global mean so rare categories can't memorize the label; learned embeddings for neural models; hashing; or grouping rare values into 'other' and using a coarser hierarchy such as region instead of zip. CatBoost and LightGBM handle categories natively. I'd always plan for unseen values at serving with a default bucket, and validate with a time-based split to check that the encoding isn't leaking.",
 ["feature-engineering","data-leakage","edge-cases"],["high-cardinality"],"case"),
Q("ml-015","Two of your features are 0.95 correlated. Does that matter for a linear model? For XGBoost? For explaining the model?","ML","medium",C,"Mid-level DS interview",
 [("What happens to the coefficients of a linear model?","test coefficient instability and variance inflation"),
  ("What happens to SHAP values or feature importance?","test importance being split between correlated features"),
  ("When would you remove one of them?","test practical judgment")],
 "Correlation hurts interpretation more than prediction. Predictions stay fine, but credit gets split arbitrarily between the correlated features.",
 "Remove one of them, since correlated features are bad.",
 "For prediction, mostly no: a regularized linear model and a boosted model predict about as well. In a linear model the coefficients become unstable with large standard errors, so individual signs and sizes can't be trusted even though the combined effect is fine; ridge regularization or dropping one helps. Trees use whichever feature gives the split first, so importance gets split or flips between runs. For explanation, SHAP divides credit between them, so I'd report them as a group or remove one. I drop a feature when interpretation, collection cost or stability matters, not as a reflex.",
 ["feature-engineering","explainability","model-selection"],["multicollinearity","xgboost","feature-importance"],"concept"),
Q("ml-016","You need to choose a decision threshold for a model that flags customers for a retention discount. How do you pick it?","ML","hard","common in senior DS interviews","Senior DS interview, applied ML",
 [("What inputs do you need beyond the model itself?","test costs and benefits: discount cost, saved-customer value, effect of the offer"),
  ("Why might 0.5 be a bad default?","test base rates and costs"),
  ("How would you revisit the threshold over time?","test monitoring and base-rate shifts")],
 "The best threshold comes from business costs and benefits, not from the model's metrics alone.",
 "Pick the threshold that maximizes F1.",
 "I'd turn it into expected value: flagging a customer costs the discount, and pays off only if the customer would have churned and the discount saves them. So I need the cost of the offer, the value of a saved customer and the discount's actual effect on churn, ideally from an experiment, since a high churn probability doesn't mean a customer is persuadable. Then I sweep thresholds on held-out data using calibrated probabilities, choose the one that maximizes expected profit, and check capacity limits such as how many offers the team can send. 0.5 is arbitrary and F1 treats the two errors as equally costly. I'd re-tune when base rates or costs shift.",
 ["cost-sensitive-decisions","evaluation-metrics","calibration"],["decision-threshold","precision-recall"],"case"),
Q("ml-017","Your regression model has a high R-squared, but the residuals fan out as predictions get larger. What does that mean, and what do you do?","ML","hard",C,"Senior DS interview, regression focus",
 [("What does it do to your confidence intervals?","test heteroscedasticity and inference"),
  ("What transformations or models would you try?","test log transform, weighted least squares, robust errors"),
  ("Does it matter if you only care about point predictions?","test linking diagnostics to purpose")],
 "A high R-squared doesn't mean the model's assumptions hold. Fanning residuals mean error grows with the level, which breaks uncertainty estimates and signals missing structure.",
 "The model is overfitting.",
 "Fanning residuals mean the error variance rises with the predicted value, known as heteroscedasticity. Point predictions can stay unbiased, but standard errors and confidence and prediction intervals are wrong, and large values may be fit worse in relative terms. I'd plot residuals against fitted values and against each feature, then try modelling the log of the target (common for money), weighted least squares, robust standard errors, or a model that predicts spread too, such as quantile regression. If only point accuracy matters it may be tolerable, but I'd check that the metric reflects relative error and not just absolute error.",
 ["model-selection","debugging","confidence-intervals"],["residual","r-squared"],"case"),
Q("ml-018","You have 200 labeled examples per class and cross-validation shows 98% accuracy. Do you trust it?","ML","hard",C,"Senior DS interview, small-data problem",
 [("What can go wrong with cross-validation on a small dataset?","test the variance of the estimate and tuning on the same folds"),
  ("How would you get a more honest estimate?","test nested CV, repeated CV and a final holdout"),
  ("What would you check about the data itself?","test duplicates, leakage and group structure")],
 "A high score on a small dataset is more often a sign of leakage, duplicates or tuning on the evaluation folds than of a great model.",
 "98% is great, so deploy it.",
 "Not yet. With 400 examples a single cross-validation estimate is very uncertain, so I'd report an interval and use repeated or stratified CV. Scores that high on small data usually point to a problem: duplicate or near-duplicate rows across folds, grouped data (the same patient or customer) split across folds, a feature that encodes the label, or hyperparameters tuned on the same folds. I'd use grouped splits, nested CV for tuning and a final untouched holdout. I'd also compare with a trivial baseline, read the confusion matrix, and ask whether real-world data resembles this sample.",
 ["validation-strategy","data-leakage","edge-cases"],["cross-validation","sample-size"],"case"),
])
