from h import *
C="common in DS interviews"
S="common in senior DS interviews"
write("prodml", [
Q("prodml-008","What's the difference between data drift and concept drift? Give a real example of each.","Production ML","easy",C,"Phone screen, ML in production",
 [("Which one can you detect without labels?","test that input drift is visible from inputs alone while concept drift needs labels or proxies"),
  ("Can a model be hurt by data drift without any concept drift?","test nuance about where the model is weak"),
  ("What do you do differently when you see each?","test mapping the diagnosis to an action")],
 "Data drift changes the inputs. Concept drift changes the relationship between inputs and outcome. They call for different checks and different fixes.",
 "Data drift is when the data changes and concept drift is when the concept changes.",
 "Data (covariate) drift: the distribution of inputs shifts, for instance a lending model sees more young applicants after a marketing campaign. Concept drift: the same inputs now imply a different outcome, for instance the same applicant profile defaults more often after a rate rise. Data drift is visible from inputs alone with PSI or KS tests; concept drift needs labels or a proxy, so it shows up later. Data drift only hurts if the model lands in a region where it is weak, while concept drift always hurts. For data drift I'd check segment performance and consider reweighting or retraining; for concept drift I'd retrain on recent data and revisit the features.",
 ["distribution-shift","explaining-concepts"],["model-drift"],"concept"),
Q("prodml-009","A loan approval model only observes repayment for the people it approved. Months later you retrain on that data. What goes wrong?","Production ML","medium",S,"Senior DS interview, lending or risk",
 [("How would you measure the damage?","test counterfactual evaluation and holdouts"),
  ("What would you change in how the data is collected?","test exploration, random approvals and reject inference"),
  ("What risk does this create in production over time?","test feedback loops and compounding")],
 "The model's own decisions determine which outcomes you ever see, so training on those outcomes bakes in its past blind spots.",
 "The data is biased, so we should collect more of it.",
 "The training set only contains applicants the old model liked, so the new model never learns what happens to the ones it rejected, and its estimates for that region are extrapolation. If the old model wrongly rejected good applicants, you will never find out, and the loop reinforces itself. Mitigations: approve a small random slice of borderline applicants (exploration within risk limits) to get unbiased labels; use reject inference techniques with clear caveats; evaluate on that random holdout instead of on approved-only data; and track population coverage. I'd also tell the business what is unknowable and what that costs.",
 ["feedback-loops","causal-inference","edge-cases"],["training-data"],"case"),
Q("prodml-010","Do you retrain a production model on a schedule, on a trigger, or continuously? How do you decide?","Production ML","medium",C,"Mid-level DS interview, ML in production",
 [("What signals would trigger a retrain?","test monitoring-based triggers"),
  ("How do you make sure a retrained model is actually better?","test champion-challenger and time-forward backtests"),
  ("What can go wrong with retraining too often?","test instability, chasing noise and cost")],
 "Retraining cadence is a trade between staleness, cost and risk. Whatever the cadence, the new model must beat the current one on fresh data before it ships.",
 "Retrain monthly.",
 "I'd choose by how fast the world changes versus how costly retraining and validation are. A schedule is simple and predictable and works when drift is gradual; a trigger (drift metric, performance drop, new data volume) saves cost when changes are irregular; continuous learning fits fast-changing, low-risk domains but is the hardest to control. Whatever the policy, a retrained model should be validated against the current one on a time-forward holdout, shadowed or canaried, and promoted only if better, with rollback ready. Retraining too often adds noise, cost and instability, so I'd start with a schedule plus alerts and adapt.",
 ["retraining","tradeoffs","model-monitoring"],["retraining","model-drift"],"case"),
Q("prodml-011","Explain how you'd use PSI to detect drift on a feature. What thresholds would you use, and where does it fall short?","Production ML","medium",C,"Mid-level DS interview, monitoring",
 [("How do you choose the bins?","test sensitivity to binning"),
  ("What does a high PSI tell you, and what doesn't it?","test not equating drift with harm"),
  ("What would you use for a large set of features?","test alternatives and aggregation")],
 "PSI tells you an input distribution moved, not whether the model got worse. Thresholds are conventions, not laws.",
 "PSI above 0.2 means there is drift, so retrain.",
 "Bin the feature using the training distribution (quantiles for numeric features), compute the proportion in each bin for training and for the recent window, and sum (current minus reference) times ln(current over reference). The usual rule of thumb is under 0.1 stable, 0.1 to 0.25 moderate, above 0.25 large, but these are heuristics that depend on the bins and the sample size. PSI is blind to shifts within a bin, unstable for sparse bins, and says nothing about whether performance suffered. I'd combine it with a KS test or Wasserstein distance, weight by feature importance, monitor the prediction distribution too, and investigate before retraining.",
 ["distribution-shift","model-monitoring","tradeoffs"],["psi"],"concept"),
Q("prodml-012","A teammate proposes a feature store. How do you decide whether it's worth building?","Production ML","medium",S,"Senior DS interview, ML platform",
 [("What problems does it solve, and what does it cost?","test benefits versus operational overhead"),
  ("When would you say not yet?","test pragmatic restraint"),
  ("How does it relate to training-serving skew?","test linking to skew")],
 "A feature store pays off when many models share features or when online and offline features must match. For one batch model it is overhead.",
 "Yes, feature stores are best practice.",
 "I'd ask what pain we have today: features recomputed by several teams, inconsistent definitions, training-serving skew from separate offline and online code, or slow onboarding of new models. A feature store addresses these with shared definitions, point-in-time correct training data and consistent online serving. The costs are real: infrastructure, ownership, backfills and migration effort. For a few batch models on one team, well-organized warehouse tables and shared code are enough. I'd recommend one when there are several models, real-time serving needs or repeated skew incidents, and start with a pilot on one high-value feature set.",
 ["training-serving-skew","feature-engineering","tradeoffs"],["feature-store","training-serving-skew"],"design"),
Q("prodml-013","Your fraud model's precision falls from 80% to 55% within a week, with no code changes. Walk me through the first 24 hours.","Production ML","hard",S,"Senior DS interview, incident response",
 [("What do you check before touching the model?","test looking at data pipelines and upstream changes first"),
  ("How do you tell a real change in fraud patterns from a data issue?","test separating causes"),
  ("What do you tell stakeholders in the first few hours?","test communication under uncertainty")],
 "Start from the cheapest explanations, upstream data and labeling changes, before model drift. Keep the business informed while you investigate.",
 "Retrain the model on recent data.",
 "First hour: confirm the drop is real. Has the label or metric definition changed, and how mature are the labels? Then check upstream: schema changes, null rates and distributions of key features, new data sources, broken joins and traffic mix. Next, slice precision by segment, channel, merchant and time to find where it dropped; a sharp step on one day suggests a pipeline or product change, a gradual slide suggests adversaries adapting. Meanwhile I'd tell stakeholders the impact (extra false positives and customer friction) and an interim mitigation such as raising the threshold. Only after diagnosing would I retrain.",
 ["fraud-detection","model-monitoring","debugging"],["fraud-detection","precision-recall"],"case"),
Q("prodml-014","How would you design monitoring for 40 models owned by 10 teams without drowning everyone in alerts?","Production ML","hard",S,"Senior or staff DS interview, ML platform",
 [("Which signals are standard for every model, and which are model-specific?","test tiered monitoring"),
  ("How do you decide who gets paged?","test ownership and severity"),
  ("How do you know your alerts are any good?","test measuring alert quality")],
 "Alerting is a product with users. Standard defaults, clear ownership and severity tiers matter more than the number of metrics tracked.",
 "Set up dashboards and alerts for accuracy and drift on every model.",
 "I'd define a shared baseline for all models: data freshness and volume, schema and null checks, prediction distribution, latency and error rate, and performance once labels arrive. Models then add their own business metrics. Alerts get severity tiers: page only for outages or clear customer harm, ticket for slow degradation, dashboard for the rest, each with a named owner and a runbook. To avoid fatigue I'd tune thresholds on history, group related alerts, and review alert precision (what fraction needed action) each quarter, retiring noisy ones. A central platform, with team-owned response.",
 ["alerting","governance-and-process","designing-systems"],["alerting","monitoring"],"design"),
Q("prodml-015","Reviewers override your model's recommendation 30% of the time. What do you do with that signal?","Production ML","hard",S,"Senior DS interview, human-in-the-loop systems",
 [("What could a 30% override rate mean?","test generating several interpretations"),
  ("How could the overrides become training data, and what are the risks?","test label quality and feedback loops"),
  ("What if reviewers stop looking and just accept the model?","test automation bias")],
 "Overrides are valuable but ambiguous. They could be model errors, reviewer preferences or missing context, so investigate before treating them as labels.",
 "Retrain the model using the overrides as labels.",
 "First I'd work out what the overrides mean by slicing them by reviewer, case type and model confidence. Heavy overrides concentrated in one segment suggest the model is wrong there; scattered overrides from a few reviewers suggest preference or inconsistency; overrides explained by information the model doesn't see suggest a missing feature. I'd audit a sample against real outcomes, where they exist, to see who is right. Using overrides as labels is useful but risky: they carry reviewer biases, and if reviewers anchor on the model the signal is contaminated. I'd also watch the opposite failure, rubber-stamping, by measuring agreement on cases where the model is known to be wrong.",
 ["feedback-loops","model-monitoring","stakeholder-communication"],["human-review"],"case"),
])
