from h import *
C="common in DS interviews"
write("python", [
Q("python-007","What are the differences between a list, a tuple, a set and a dict, and how do you decide which to use?","Python","easy",C,"Phone screen, Python fundamentals",
 [("You need to check membership in a collection of a million items many times. What do you use, and why?","test complexity awareness (hash lookup versus scan)"),
  ("Can a list be a dictionary key? Why or why not?","test hashability and mutability"),
  ("When would a tuple be better than a list?","test immutability and semantics")],
 "The choice is mostly about lookup cost and mutability, not syntax.",
 "Lists are ordered and mutable, tuples are immutable, sets hold unique values, and dicts store key-value pairs.",
 "List: ordered, mutable, linear-time membership. Tuple: ordered and immutable, hashable if its contents are, good for fixed records and dict keys. Set: unordered unique items with average constant-time membership. Dict: key-value mapping with average constant-time lookup, insertion-ordered in modern Python. For repeated membership checks on a million items I convert the list to a set once, because a list would scan every item on each check. Lists cannot be dict keys because they are mutable and unhashable. I choose by the access pattern: ordered iteration, fast lookups, deduplication or a fixed record.",
 ["python-fundamentals","explaining-concepts"],["data-structure"],"concept"),
Q("python-008","You run df[df['score'] > 0]['label'] = 1 in pandas. Either nothing changes or you get a warning. What's going on, and how do you do it properly?","Python","easy",C,"Phone screen, pandas",
 [("How does this relate to views and copies?","test understanding of pandas internals"),
  ("What is the safest pattern for conditional assignment?","test .loc and np.where"),
  ("What changes with copy-on-write in recent pandas versions?","test awareness of recent pandas behavior")],
 "Chained indexing may operate on a temporary copy, so the assignment can silently go nowhere. Assign with a single .loc call instead.",
 "Use .copy() to make the warning go away.",
 "The expression first selects rows, which can return a copy, and then assigns the column into that temporary object, so the original DataFrame never changes, or pandas warns that it can't tell. The fix is a single indexing call: df.loc[df['score'] > 0, 'label'] = 1, or np.where when creating a column. Silencing the warning or adding .copy() only hides the problem. In recent pandas, copy-on-write means chained assignment never modifies the original, which removes the ambiguity but breaks old code that relied on it. I'd make writes explicit and cover them with a test.",
 ["pandas","debugging","python-fundamentals"],["dataframe"],"case"),
Q("python-009","Write a function that computes precision and recall from lists of true and predicted labels. Which edge cases do you handle?","Python","medium",C,"Coding round, ML-focused role",
 [("What should it return when there are no positive predictions?","test zero-division handling and what it means"),
  ("How would you extend it to multiple classes?","test micro versus macro averaging"),
  ("How would you test it?","test comparing against a trusted library")],
 "The formulas are trivial. The value is in deciding what a zero denominator means and testing against a trusted implementation.",
 "Count true positives, false positives and false negatives with a loop, then divide.",
 "Count TP, FP and FN in one pass over zip(y_true, y_pred); precision = TP / (TP + FP) and recall = TP / (TP + FN). Edge cases: unequal lengths should raise an error, no predicted positives leaves precision undefined, and no actual positives leaves recall undefined. I'd return 0.0 or NaN explicitly and document it, like a zero_division parameter, instead of letting ZeroDivisionError happen. For multiclass I'd compute per class and report macro, micro or weighted averages depending on whether rare classes matter. I'd test against sklearn on random inputs plus hand-built degenerate cases.",
 ["evaluation-metrics","python-fundamentals","software-testing"],["precision-recall"],"implementation"),
Q("python-010","What is a generator in Python, and when would you use one instead of a list in a data pipeline?","Python","medium",C,"Coding round, Python fundamentals",
 [("What can you not do with a generator that you can do with a list?","test one-pass iteration and no indexing or length"),
  ("How would you read and transform a huge file in stages without loading it?","test chaining generators"),
  ("What bug appears if you iterate a generator twice?","test exhaustion")],
 "A generator produces values one at a time on demand, so memory stays flat no matter how much data flows through, at the price of single-pass access.",
 "A generator uses yield and saves memory compared to a list.",
 "A generator is a function (or expression) that yields values lazily: it computes the next item only when asked, so memory use does not grow with the data. That suits pipelines that read a large file line by line, transform each record, and write it out, since stages can be chained without ever holding everything. The trade-offs: you can iterate once, you can't index or take len() without consuming it, and iterating twice silently yields nothing the second time, a classic bug. If I need several passes or random access I materialize a list or reload the source. For heavy numeric work I'd still prefer vectorized operations on chunks over item-at-a-time loops.",
 ["python-fundamentals","performance-at-scale"],["memory-footprint","data-pipeline"],"concept"),
Q("python-011","Write a function that returns the k most frequent items from a very large list or stream.","Python","medium",C,"Coding round",
 [("What are the time and memory costs of your approach?","test complexity analysis"),
  ("What if the stream has too many distinct items to store?","test approximate algorithms"),
  ("How do you break ties?","test specifying ambiguous behavior")],
 "Counting is linear. The choice of how to pick the top k decides whether you sort everything or keep a small heap.",
 "Count with a dictionary, sort by count and slice the first k.",
 "Count with collections.Counter in linear time, then use heapq.nlargest(k, counts.items(), key=...), which costs O(m log k) for m distinct items instead of sorting all of them; Counter.most_common(k) does this. Memory is proportional to the number of distinct items. If a stream has too many distinct values to hold, I'd switch to an approximate method such as a Count-Min Sketch with a heap, or the Misra-Gries algorithm, and say that counts become estimates. I'd also define tie-breaking (alphabetical or first seen) so results are deterministic.",
 ["python-fundamentals","performance-at-scale"],["stream-processing"],"implementation"),
Q("python-012","What happens when you write def add_item(x, items=[])? Have you hit this in real code?","Python","easy",C,"Phone screen, Python gotchas",
 [("How would you fix it?","test the None sentinel pattern"),
  ("Why does Python behave this way?","test understanding that defaults are evaluated once at definition time"),
  ("Where does the same trap show up with dataclasses?","test field(default_factory=...)")],
 "Default values are created once, when the function is defined, so a mutable default is shared across every call.",
 "The list keeps its old values between calls, so use None instead.",
 "The default list is evaluated once at definition time and stored on the function, so every call that omits items mutates the same list. Items leak across calls, and in a long-running service even across users. The standard fix is items=None and then items = [] inside the function when it is None. The same trap affects dicts, sets and dataclass fields, where field(default_factory=list) is the equivalent. It is a good example of a bug that tests miss: each test passes alone but fails when run in a different order.",
 ["python-fundamentals","debugging"],["default-argument"],"concept"),
Q("python-013","You cleaned data in a notebook. How do you turn that code into something your team can trust in production?","Python","hard","common in senior DS interviews","Senior DS interview, production focus",
 [("What would you test, and how?","test unit tests and data validation"),
  ("How do you make sure training and production run the same code?","test avoiding duplicated logic"),
  ("What do you do with the notebook itself?","test pragmatic handling and documentation")],
 "Production means functions with explicit inputs and outputs, tests, validation of the data they receive, and one code path shared by training and serving.",
 "Copy the cells into a Python file and schedule it.",
 "I'd refactor the cells into pure functions with explicit inputs and outputs and no hidden notebook state, put them in a package with pinned dependencies, and add unit tests for edge cases such as empty frames, NaNs and unexpected categories. I'd add data validation at the boundary (schema, ranges, null rates) that fails loudly with a clear message. The same functions must serve training and inference to avoid skew. Add logging, config instead of hardcoded paths, code review and a CI run. The notebook stays as documentation or exploration and calls the package rather than owning the logic.",
 ["software-testing","versioning-reproducibility","data-quality"],["unit-testing","data-validation"],"case"),
Q("python-014","You need to compute features over 50 million rows in Python. How do you parallelize it, and what limits you?","Python","hard",C,"Senior DS interview, performance focus",
 [("Why can threads fail to speed up CPU-bound Python code?","test understanding of the GIL"),
  ("What overhead does multiprocessing add?","test serialization and memory costs"),
  ("When would you move off a single machine?","test the decision to use Spark or a warehouse")],
 "Work out first whether the job is CPU-bound or I/O-bound, and whether it can be done in vectorized or SQL form before adding processes.",
 "Use multiprocessing to split the data across cores.",
 "First I'd check whether it can be vectorized with pandas, NumPy or Polars, or pushed to the warehouse as SQL, which often beats naive parallel Python by a wide margin. If it is CPU-bound and has to be Python, use processes, because the GIL stops threads from running Python bytecode in parallel; threads suit I/O-bound work. Multiprocessing has costs: pickling data between processes, duplicated memory and per-task overhead, so I'd partition into large chunks and avoid shipping big objects around. Beyond one machine I'd use Spark, Dask or the warehouse. And I'd profile first so I parallelize the real bottleneck.",
 ["performance-at-scale","python-fundamentals","feature-engineering"],["parallelism"],"case"),
])
