from h import *
C="common in DS interviews"
S="common in senior DS interviews"
write("system-design", [
Q("system-design-007","Design a system that forecasts weekly cash collections for 20 business units.","System Design","medium",S,"Senior DS interview, finance analytics",
 [("Would you build one model or twenty? How do you decide?","test global versus per-unit models and hierarchy"),
  ("How do you keep unit forecasts consistent with the company total?","test hierarchical reconciliation"),
  ("How would the finance team use and challenge the forecast?","test explainability and workflow")],
 "The model is the smaller part. Hierarchy, backtesting, data freshness and how finance will challenge the numbers drive the design.",
 "Train a time-series model for each business unit and run it weekly.",
 "I'd start with the decision: the horizon, the accuracy needed and who acts on it. Data: invoices, payment terms, collection history and calendar effects, from a pipeline with freshness and quality checks. Modelling: a global gradient-boosted model with unit features usually beats twenty small series, with a simple per-unit baseline to compare against; hierarchical reconciliation keeps unit forecasts summing to the total. Evaluation: rolling-origin backtests by horizon, tracking error by unit. Serving: a weekly batch with forecast intervals, versioned outputs, and a view where finance can see drivers and adjust assumptions. Monitoring compares forecasts to actuals as they land and alerts on drift.",
 ["time-series-forecasting","designing-systems","batch-vs-realtime"],["forecasting","forecast-horizon"],"design"),
Q("system-design-008","Design a customer churn early-warning system that a retention team uses every week.","System Design","medium",C,"DS interview, subscription or fintech company",
 [("How do you define churn so the label is usable?","test label definition and prediction window"),
  ("How do you turn scores into actions the team can take?","test linking predictions to interventions and capacity"),
  ("How do you measure whether the interventions actually helped?","test holdouts and uplift thinking")],
 "A churn score is only useful if it is tied to an action and a measured result. The prediction is the smallest part of the system.",
 "Train a churn classifier on past customers and send the retention team the top scores.",
 "I'd start with the decision: what can the retention team do, how many customers per week, and how early they need warning. That fixes the churn definition (for example no activity for 60 days) and the prediction window, so labels are usable and not leaked. Features come from usage, billing and support history, built point-in-time in a weekly batch. The model outputs calibrated probabilities, and a layer on top ranks customers by expected value (likelihood times customer value) within the team's capacity, with reasons for each flag. A random holdout group receives no outreach so we can measure real impact, and results feed back into evaluation. Monitoring covers drift, calibration and the outreach results.",
 ["retention-cohorts","designing-systems","batch-vs-realtime","cost-sensitive-decisions"],["churn","retention"],"design"),
Q("system-design-009","Design a credit limit decision system whose decisions must be explainable to customers and regulators.","System Design","hard",S,"Senior DS interview, lending or regulated industry",
 [("How do you produce reasons for a decision that a customer can understand?","test explanation methods and their limits"),
  ("How do you monitor the system for unfair outcomes?","test fairness monitoring across groups"),
  ("How do you approve and record a model change?","test governance, versioning and audit trails")],
 "In a regulated setting the model is only one component. Reasons, fairness checks, change approval and an audit trail are part of the product.",
 "Use a gradient-boosted model and explain it with SHAP.",
 "I'd start with constraints: which inputs are legally allowed, what reasons must be given, and who has to approve changes. Modelling choice is a trade: a constrained or monotonic model (or a scorecard) is easier to defend, while a boosted model with post-hoc explanations may perform better but needs validation that explanations are stable and honest. Each decision stores the inputs, model version, score and top reasons, so any outcome can be reproduced and explained. I'd monitor approval rates and errors across protected groups, plus drift and calibration, and set review gates for model changes with documentation and sign-off from risk and compliance. A human override path handles exceptions.",
 ["explainability","fairness","governance-and-process","designing-systems"],["feature-importance","algorithmic-fairness","disparate-impact"],"design"),
Q("system-design-010","Design a metrics layer so every team computes revenue, active users and churn the same way.","System Design","medium",C,"DS or analytics engineering interview",
 [("Where do metric definitions live, and who can change them?","test ownership and review of definitions"),
  ("How do you handle a definition that needs to change?","test versioning and communicating changes"),
  ("How do you check that dashboards match the layer?","test reconciliation and tests")],
 "A metrics layer is a governance problem as much as a technical one. One reviewed definition per metric, versioned, with tests that catch disagreement.",
 "Create a shared table with the metrics so everyone queries the same numbers.",
 "I'd define each metric once, as code in version control, with its grain, filters, time logic and owner, and have dashboards, notebooks and models read through that layer rather than rewriting the SQL. Changes go through review by the owner and the main consumers, and are versioned, with a changelog and a transition period so historical comparisons are not silently broken. Automated tests check the definitions against known totals and compare dashboard outputs to the layer. The layer also handles shared dimensions such as customer segment and time zone. I'd start with the five metrics that cause the most disagreement and expand once teams trust them.",
 ["data-quality","governance-and-process","designing-systems"],["churn","data-pipeline"],"design"),
Q("system-design-011","Design a daily pipeline that ingests transactions from five source systems with inconsistent schemas.","System Design","medium",C,"DS or data engineering interview",
 [("How do you detect and handle a schema change at one source?","test schema validation and data contracts"),
  ("What happens when a run fails halfway?","test idempotency and retries"),
  ("How do you reconcile the five sources to the same numbers?","test reconciliation and quality checks")],
 "Reliability comes from idempotent loads, validation at the boundary and reconciliation, not from the transformation logic.",
 "Write a script per source and combine them into one table.",
 "Land each source's raw data unchanged in a staging area, then transform it into a common canonical schema with explicit mappings and tests. Validate at the boundary: schema, types, null rates, ranges and row counts against expectations, quarantining bad records instead of failing the whole run. Make loads idempotent (partition overwrite or merge on a key) so reruns are safe, orchestrate with retries and alerting, and keep backfills possible. Add reconciliation checks, such as daily totals against each source's control totals, and data contracts with source owners so schema changes are announced. Version the mappings and document lineage.",
 ["data-quality","versioning-reproducibility","designing-systems"],["data-pipeline","data-validation"],"design"),
Q("system-design-012","Design an anomaly detection system for key business metrics that analysts will actually trust.","System Design","hard",S,"Senior DS interview, analytics platform",
 [("How do you handle seasonality and holidays?","test baselines that account for them"),
  ("How do you keep false alarms down?","test thresholds and feedback"),
  ("What would you show alongside an alert?","test explanation and root-cause hints")],
 "Trust comes from low false alarms and context. An alert that says where the change is and whether it was expected gets used, and a bare red flag gets muted.",
 "Use a z-score and alert when a metric is three standard deviations from the mean.",
 "Start with which metrics matter and the cost of a miss versus a false alarm. Model an expected value that accounts for trend, weekly and yearly seasonality and holidays, such as a forecast with prediction intervals instead of a flat mean, and flag points outside the interval. Reduce noise with minimum-impact thresholds, persistence requirements and grouping of related alerts. With each alert show the metric against its expected range, the segments driving the change (dimension drill-down) and recent related changes such as deployments or data delays, because many anomalies are broken pipelines. Add a feedback button to mark alerts useful or not, track alert precision, and review regularly.",
 ["model-monitoring","alerting","tradeoffs"],["anomaly-detection","monitoring"],"design"),
Q("system-design-013","Design a semantic search system over 5 million internal documents.","System Design","hard",S,"Senior DS or ML engineer interview, LLM applications",
 [("How do you chunk and index the documents?","test chunking, metadata and embeddings"),
  ("When does pure vector search fail, and what do you add?","test hybrid search with keywords and reranking"),
  ("How do you handle permissions?","test per-user access control")],
 "Retrieval quality depends on chunking, hybrid ranking and access control more than on the choice of vector database.",
 "Embed the documents and store them in a vector database.",
 "Ingest: parse documents, split them into chunks that preserve meaning with some overlap and metadata (title, source, date, owner), embed each chunk, and store vectors in an approximate nearest-neighbor index alongside the text. Query: embed the query, retrieve candidates, and combine with keyword search (BM25), since exact terms, codes and names are handled poorly by embeddings alone; rerank the top results with a cross-encoder. Enforce permissions at retrieval by filtering on access metadata, not after generation. Keep the index fresh with incremental updates. Evaluate with a labeled set of queries (recall at k, mean reciprocal rank) plus user feedback. Latency and cost scale with index size and reranking depth.",
 ["embeddings-and-search","rag","designing-systems","latency-and-cost"],["embedding","latency"],"design"),
Q("system-design-014","Design a what-if scenario tool that lets finance teams see how a forecast changes under different assumptions.","System Design","medium",C,"DS interview, finance analytics",
 [("How do you make the forecast respond to assumptions the model has never seen?","test combining models with driver-based rules"),
  ("How do you show uncertainty?","test intervals and ranges"),
  ("How do you make sure users don't treat scenarios as predictions?","test communication")],
 "A what-if tool is an explanation tool. Users must see which drivers move the number and understand that scenarios aren't predictions.",
 "Let users change the inputs and rerun the model.",
 "Separate the baseline forecast from a scenario layer: a driver-based structure (volume, price, payment terms, collection rates) that the ML forecast feeds or calibrates, so users change meaningful business levers rather than raw model features, which can produce nonsense outside the training range. Changes are saved as named, versioned scenarios, compared against the baseline, with a waterfall showing each driver's contribution. Show forecast intervals and flag assumptions outside historical ranges. Make recomputation fast with precomputed components or a lightweight surrogate. Label scenarios as 'if' statements, record who changed what, and let finance override with comments.",
 ["time-series-forecasting","explainability","designing-systems","stakeholder-communication"],["scenario-analysis","forecasting"],"design"),
])
