from h2 import *
C="common in DS interviews"; S="common in senior DS interviews"; N="increasingly common"
write("spread", [
Q("stats-016","What is maximum likelihood estimation, and why does it show up in so many models?","Statistics","medium",C,"DS interview, statistics foundations",
 [("Why do we maximize the log-likelihood instead of the likelihood?","test numerical stability and sums over independent points"),
  ("How does logistic regression's loss relate to likelihood?","test the link between cross-entropy and Bernoulli likelihood"),
  ("When does maximum likelihood go wrong?","test small samples, separation and overfitting")],
 "Maximum likelihood picks the parameters that make the observed data most probable; many familiar loss functions are negative log-likelihoods in disguise.",
 "It finds the parameters that best fit the data by maximizing the probability of the data.",
 "Given a model with parameters, the likelihood is the probability it assigns to the data we saw. Maximum likelihood chooses the parameters that maximize it. For independent points the likelihood is a product, so we maximize the log, which turns it into a sum and avoids underflow. Squared error is the negative log-likelihood of Gaussian noise, and cross-entropy is the negative log-likelihood of Bernoulli labels, so training those models is maximum likelihood. It can fail with little data, where it overfits, and with perfectly separable classes, where logistic coefficients diverge; priors or regularization fix both.",
 ["maximum-likelihood"],["likelihood"],"concept"),
Q("stats-017","You have conversion data for four marketing channels. How do you test whether they differ, and what do you do after a significant result?","Statistics","medium",C,"Marketing analytics case",
 [("Why not run six pairwise tests?","test multiple comparisons"),
  ("What assumptions does a chi-square test make?","test independence and expected counts"),
  ("How would the approach change for a continuous outcome like revenue per user?","test ANOVA and non-normal data")],
 "An omnibus test says whether any channels differ; you then need a corrected follow-up to say which, and a size of effect to say whether it matters.",
 "I would run a chi-square test on the conversion counts and then compare channels in pairs.",
 "Conversions are counts in a channel-by-outcome table, so a chi-square test of independence asks whether conversion rate depends on channel. It needs independent users and reasonably large expected counts; otherwise use Fisher's exact test. A significant result only says some channels differ. To find which, I'd run pairwise comparisons with a correction such as Holm or Tukey rather than six uncorrected tests, and report effect sizes with intervals, since a huge sample makes tiny differences significant. For revenue per user the analogue is ANOVA, or a rank-based test if the data are heavily skewed.",
 ["categorical-tests","multiple-testing","hypothesis-testing"],["chi-square-test","p-value"],"case"),
Q("stats-018","When would you use a multi-armed bandit instead of a standard A/B test?","Statistics","hard",S,"Senior DS interview, experimentation",
 [("What do you give up compared with a fixed-horizon A/B test?","test inference trade-offs"),
  ("How does Thompson sampling decide what to show?","test the mechanism"),
  ("What goes wrong if the effect changes over time?","test non-stationarity")],
 "Bandits trade clean inference for lower regret, so they suit cheap, short-lived decisions where you care about outcomes during the test, not about a precise estimate afterwards.",
 "A bandit sends more traffic to the better option while it learns, so you lose less.",
 "A bandit shifts traffic toward better-performing variants as evidence accumulates, which cuts the cost of showing a loser. That fits headline testing, promotions and recommendations, where options are many, decisions are short-lived and the goal is reward, not a report. An A/B test fits product changes where you need an unbiased estimate, a guardrail check and a decision you can defend. With a bandit the unequal, adaptive allocation makes estimates for the weaker arms noisy and biased and complicates p-values. Thompson sampling draws a plausible rate for each arm from its posterior and plays the best draw. If the effect drifts, for example by day of week, a bandit can lock onto a stale winner unless it discounts old data.",
 ["bandits","ab-testing"],["multi-armed-bandit","ab-test"],"concept"),
Q("stats-019","A subscription product wants to understand churn, but many customers are still subscribed. How do you analyze time-to-churn?","Statistics","hard",S,"Senior DS interview, retention analysis",
 [("What is censoring and why is it a problem for a simple average?","test right-censored data"),
  ("What does a Kaplan-Meier curve show?","test the estimator"),
  ("How would you include features like plan type?","test Cox proportional hazards")],
 "Customers who haven't churned yet are not missing data; they are partial information, and dropping them or treating them as lifetimes biases the answer short.",
 "I would calculate the average time until customers cancel.",
 "Customers who are still active have an unknown churn time: we only know it is longer than what we have observed. Averaging observed lifetimes of churned customers biases the answer downward, and treating active customers as churned at today's date is also wrong. Survival analysis handles this censoring. A Kaplan-Meier curve estimates the share still subscribed at each tenure, and I would compare curves by plan or cohort. To include features I'd use a Cox proportional hazards model, which gives hazard ratios, after checking that the proportionality assumption holds. If the goal is a score for who will churn in the next 30 days, a classifier on a fixed window can be simpler.",
 ["survival-analysis","retention-cohorts"],["churn"],"case"),
Q("ml-019","How does an ARIMA model forecast, and when would you still use it?","ML","medium",C,"DS interview, forecasting",
 [("What do the p, d and q mean?","test the components"),
  ("Why does the series need to be stationary?","test differencing"),
  ("How do you pick the orders?","test ACF and PACF, information criteria and validation")],
 "ARIMA forecasts a single series from its own past values and past errors after differencing it to be stable; it is a strong baseline for short, regular series.",
 "ARIMA uses past values of the series to predict future values.",
 "ARIMA combines autoregression on past values (p), differencing to remove trend (d) and a moving average of past errors (q). Differencing aims at a stationary series, whose mean and variance don't drift, because the model's coefficients assume stable relationships. I'd choose orders using autocorrelation plots and information criteria, then check them by walk-forward validation. It works well for a single, short, regular series with few external drivers and is easy to explain. It is a poor fit for many series at once, multiple seasonalities, holidays and rich external features, where boosted trees or other models do better.",
 ["forecasting-models","time-series-forecasting"],["arima","time-series"],"concept"),
Q("ml-020","You need weekly sales forecasts for 200 products. Would you use exponential smoothing, Prophet or gradient boosting?","ML","medium",C,"DS interview, forecasting case",
 [("What can boosting use that the classical models can't?","test external features and cross-series learning"),
  ("How would you evaluate the choice?","test walk-forward validation"),
  ("What would you ship first?","test baselines and pragmatism")],
 "Start with a simple baseline per series, then add a global model once you have drivers such as price and promotions that the classical methods cannot use.",
 "I would try them all and pick the one with the lowest error.",
 "Exponential smoothing is a quick, robust baseline for each series and needs little tuning. Prophet adds trend changes, seasonality and holidays with readable components, but it is not always the most accurate. Gradient boosting trains one global model across all 200 products using lag features, calendar features, price and promotions, so it can learn from related products and handle short histories. I'd compare all three with walk-forward validation on the metric the business cares about, ship the simple baseline first, and move to the global model if it wins by a margin that justifies the extra pipeline.",
 ["forecasting-models","time-series-forecasting","model-selection"],["exponential-smoothing","prophet"],"case"),
Q("ml-021","You forecast sales for each store, each region and the whole company, and the numbers don't add up. What do you do?","ML","hard",S,"Senior DS interview, forecasting at scale",
 [("What is the difference between bottom-up and top-down?","test the simple approaches"),
  ("What does reconciliation do?","test optimal combination"),
  ("How do you evaluate the result?","test accuracy at every level")],
 "Forecasts made separately at each level disagree; reconciliation adjusts them so they add up, usually improving accuracy as well as consistency.",
 "I would forecast the stores and add them up to get the region and company totals.",
 "Separate models at each level won't sum. Bottom-up sums store forecasts, which is consistent but noisy for sparse stores. Top-down splits a company forecast by historical proportions, which is smooth but loses store detail. Reconciliation methods take forecasts from every level and adjust them jointly so they add up, weighting each by how reliable it is; this often improves accuracy at all levels because each level contributes information. I would evaluate with walk-forward validation at every level, since the right choice depends on which level decisions are made at.",
 ["forecasting-models","time-series-forecasting"],["forecasting"],"design"),
Q("ml-022","Compare MAPE, RMSE and WAPE for judging a demand forecast. Which would you use?","ML","easy",C,"DS interview, evaluation metrics for forecasting",
 [("What happens to MAPE when actual values are near zero?","test blow-up and asymmetry"),
  ("Why might RMSE and MAE disagree on which model is better?","test sensitivity to large errors"),
  ("How would you match the metric to the business cost?","test cost alignment")],
 "Each metric rewards a different behavior, so choose by what an error costs the business and by whether the data contain small or zero values.",
 "I would use MAPE because percentages are easy to explain.",
 "MAPE is easy to read but explodes when actuals are near zero and penalizes over-forecasts more than under-forecasts, which can push models toward under-forecasting. RMSE squares errors, so it punishes large misses and suits cases where a big miss is disproportionately costly. WAPE divides total absolute error by total actuals, so it is stable and weights high-volume items more, which is often how the business thinks. I would pick the metric from the cost of errors, report more than one, and evaluate at the level where decisions are made.",
 ["forecast-metrics","evaluation-metrics"],["mape"],"concept"),
Q("ml-023","How would you build a recommender for an e-commerce site? Compare matrix factorization with a content-based approach.","ML","medium",C,"DS interview, recommendations",
 [("What happens for a brand-new item or user?","test the cold start problem"),
  ("Explicit ratings are rare. What do you use instead?","test implicit feedback"),
  ("How do you evaluate offline and online?","test ranking metrics and A/B tests")],
 "Collaborative methods learn from behavior but need history; content-based methods work from item attributes but stay narrow. Real systems combine them.",
 "I would use collaborative filtering to recommend what similar users bought.",
 "Matrix factorization learns a vector for each user and item from the interaction matrix so that their product predicts affinity; it captures taste patterns without needing item attributes, but it needs history and handles new items poorly. A content-based approach scores items by similarity to what a user liked using attributes or embeddings; it handles new items but tends to recommend more of the same. Most sites use implicit feedback such as clicks and purchases, and combine the approaches, often with a ranking model on top. I'd evaluate offline with ranking metrics like recall at k or NDCG, with time-based splits, and confirm with an online experiment.",
 ["recommender-systems","feedback-loops"],["matrix-factorization","embedding"],"design"),
Q("ml-024","Which models need feature scaling, and which don't? Why?","ML","easy",C,"Phone screen, ML fundamentals",
 [("What goes wrong if you fit the scaler on all the data?","test leakage"),
  ("Does scaling matter for lasso and ridge?","test penalty sensitivity"),
  ("When would you use standardization versus min-max?","test outliers and bounded ranges")],
 "Scaling matters when a model uses distances or penalizes coefficient size, or when optimization is sensitive to scale; tree models split on order and don't care.",
 "Neural networks and SVMs need scaling, trees don't.",
 "Models based on distances (k-NN, k-means, SVMs), penalized models (ridge, lasso) and gradient-based models like neural networks are sensitive to feature scale: a feature measured in large units dominates distances or gets penalized differently. Tree-based models split on thresholds, so monotonic rescaling changes nothing. I fit the scaler on the training data only and apply it to validation and test data, otherwise information leaks. Standardization is the default; min-max suits bounded inputs but is sensitive to outliers, where a robust scaler helps.",
 ["feature-scaling","data-leakage"],["feature-scaling"],"concept"),
Q("python-015","Implement k-means from scratch with NumPy. What would you check before trusting the result?","Python","medium",C,"Coding screen, ML from scratch",
 [("How would you vectorize the assignment step?","test broadcasting and avoiding loops"),
  ("What do you do with an empty cluster?","test edge cases"),
  ("How do you decide it has converged?","test stopping criteria")],
 "The algorithm is short; the care goes into initialization, empty clusters and stopping, plus running it several times because the result depends on the start.",
 "I would pick random centers, assign points and update the means in a loop.",
 "Initialize k centers by sampling points (ideally k-means++), then repeat: compute distances from every point to every center with broadcasting, assign each point to its nearest center with argmin, and set each center to the mean of its points. If a cluster is empty, re-seed it from a far-away point. Stop when assignments stop changing or the centers move less than a tolerance, with an iteration cap. Run it several times with different seeds and keep the lowest within-cluster sum of squares. Before trusting it I'd check that features are scaled and that the clusters are stable and interpretable.",
 ["python-fundamentals","clustering"],["k-means"],"implementation"),
Q("python-016","Write gradient descent for linear regression using only NumPy. How do you know the learning rate is right?","Python","medium",C,"Coding screen, ML from scratch",
 [("Why does unscaled data make this slow or unstable?","test conditioning and scaling"),
  ("How does this differ from the closed-form solution?","test the normal equation"),
  ("What changes for stochastic or mini-batch updates?","test noisy gradients")],
 "Compute the gradient of the mean squared error, step against it, and watch the loss curve: a good learning rate decreases it smoothly and a bad one diverges or crawls.",
 "I would repeatedly update the weights by subtracting the learning rate times the gradient.",
 "With X as an n by d matrix, predictions are X @ w, the gradient of mean squared error is (2/n) * X.T @ (X @ w - y), and each step is w -= lr * gradient, repeated for a fixed number of iterations or until the loss stops improving. I'd scale features first, because very different scales make the loss surface a narrow valley that forces a tiny learning rate. I'd plot loss per iteration: smooth decline means the rate is fine, oscillation or growth means it is too high, and a very slow decline means it is too low. The closed form is exact for small problems; gradient descent scales to large ones and generalizes to other models. Mini-batches trade noisier steps for much cheaper updates.",
 ["optimization","python-fundamentals"],["gradient-descent","learning-rate"],"implementation"),
Q("python-017","Build a simple document search using TF-IDF and cosine similarity. What are its limits?","Python","medium",C,"Coding screen, text processing",
 [("Why cosine similarity instead of Euclidean distance?","test length normalization"),
  ("How does it handle synonyms?","test lexical matching limits"),
  ("How would it scale to millions of documents?","test sparse matrices and indexes")],
 "TF-IDF search matches words, not meaning: fast and transparent, but blind to synonyms and paraphrase.",
 "I would convert documents to TF-IDF vectors and rank them by cosine similarity to the query.",
 "Fit a TF-IDF vectorizer on the documents to get a sparse matrix, transform the query with the same vectorizer, compute cosine similarity as a sparse dot product (rows are L2-normalized by default), and return the top-scoring documents with argsort. Cosine ignores document length, which Euclidean distance does not. The limits are that it only matches shared words, so synonyms and paraphrases are missed, and that stop words and tokenization choices matter. At large scale I'd use an inverted index such as BM25 in a search engine, or embeddings with an approximate nearest-neighbor index, often combining both.",
 ["text-features","embeddings-and-search","python-fundamentals"],["tf-idf","cosine-similarity"],"implementation"),
Q("llm-014","When would you use LoRA instead of fully fine-tuning a large language model?","LLMs & AI","medium",N,"DS/ML engineer interview, LLM adaptation",
 [("What exactly is trained in LoRA?","test low-rank adapters"),
  ("What are the trade-offs against full fine-tuning?","test capacity and cost"),
  ("Before fine-tuning at all, what would you try?","test prompting and retrieval first")],
 "LoRA freezes the base model and trains small added matrices, giving most of the benefit of fine-tuning at a fraction of the memory and storage.",
 "LoRA is cheaper than full fine-tuning because it trains fewer parameters.",
 "LoRA keeps the pretrained weights frozen and learns small low-rank matrices added to selected layers, so only a tiny share of parameters is trained. That cuts GPU memory, speeds up training and lets you store one small adapter per task and swap them on one base model. Full fine-tuning can capture larger changes in behavior but costs far more and risks forgetting. I'd use LoRA for style, format or domain adaptation with limited data and budget. Before either, I'd check whether prompting or retrieval solves the problem, since fine-tuning is better for behavior than for adding facts.",
 ["prompting-vs-fine-tuning","llm-training"],["lora","pretrained-model"],"concept"),
])
