import sys; sys.path.insert(0, sys.path[0])
from h import *
C="common in DS interviews"
write("sql", [
Q("sql-009","Write a query to find the second highest salary in an employees table.","SQL","easy",C,"Phone screen, data analyst or data scientist",
 [("What should the query return if two people tie for the highest salary?","test awareness of ties and ranking functions"),
  ("What if there is no second highest value at all?","test NULL handling and empty-result edge cases"),
  ("How would you generalize this to the Nth highest salary per department?","test generalizing with window functions")],
 "The query is easy. The real test is whether you ask what 'second highest' means when salaries tie.",
 "SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees).",
 "I'd first confirm whether 'second highest' means the second distinct value or the second row. For distinct values I use DENSE_RANK() OVER (ORDER BY salary DESC) and keep rank 2, wrapped so an empty result returns NULL if the interviewer wants a row back. The MAX-of-smaller-values version works but does not generalize. For the Nth per department I add PARTITION BY department and filter on the rank. I'd also say what ROW_NUMBER and RANK would do under ties, so the choice is deliberate.",
 ["sql-fundamentals","window-functions","edge-cases"],["ranking"],"implementation"),
Q("sql-010","Why does this query fail, and how would you fix it? SELECT dept, AVG(salary) FROM employees WHERE AVG(salary) > 50000 GROUP BY dept","SQL","easy",C,"Phone screen, SQL fundamentals",
 [("When does a filter belong in WHERE and when in HAVING, if both would give the same result?","test performance reasoning about filtering before aggregation"),
  ("What changes if you also want to exclude departments with fewer than 5 people?","test combining aggregate conditions")],
 "A filter on an aggregate cannot run before the groups exist. Knowing the order SQL evaluates clauses removes a whole class of errors.",
 "Use HAVING instead of WHERE for aggregates.",
 "WHERE filters individual rows before grouping, so an aggregate like AVG(salary) does not exist yet and the query errors. HAVING filters groups after aggregation, so the fix is GROUP BY dept HAVING AVG(salary) > 50000. Conditions on raw columns, such as excluding terminated employees, should stay in WHERE because they cut rows early and can use indexes. Using both is normal: WHERE for row filters, HAVING for group filters, for example HAVING COUNT(*) >= 5 for a minimum team size.",
 ["sql-fundamentals","explaining-concepts"],["aggregate-function"],"concept"),
Q("sql-011","Calculate month-over-month revenue growth for each product.","SQL","medium",C,"Analytics DS interview",
 [("What should the first month for each product show?","test NULL handling for the first period"),
  ("What if a product has no sales in some months?","test handling gaps in a time series"),
  ("What if last month's revenue is zero?","test divide-by-zero handling")],
 "LAG is the easy part. Missing months and zero denominators decide whether the numbers can be trusted.",
 "Use LAG(revenue) OVER (PARTITION BY product ORDER BY month) and compute (revenue - previous) / previous.",
 "Aggregate to product-month first, then use LAG partitioned by product and ordered by month. Two traps. A month with no sales has no row, so LAG would compare against the wrong month; I'd join to a calendar of months and fill gaps with zero before taking LAG. And I'd divide with NULLIF(previous, 0) so a zero base returns NULL instead of an error or infinite growth. The first month per product has no prior value and should show NULL, not 0%. I'd also ask what the stakeholder wants for tiny bases, since going from 5 to 50 dollars is a 900% jump that means little.",
 ["window-functions","sql-fundamentals","edge-cases"],["growth-rate","window-function"],"implementation"),
Q("sql-012","Find users who were active on three or more consecutive days.","SQL","hard",C,"Product analytics DS interview",
 [("How would you find each user's longest streak ever?","test generalizing the consecutive-days pattern"),
  ("What if a user has several events on the same day?","test deduplicating before the streak logic"),
  ("What if 'day' depends on the user's time zone?","test real-world date handling")],
 "Subtracting a row number from the date turns each run of consecutive days into a constant, which a plain GROUP BY can then count.",
 "Self-join the table on date + 1 and date + 2.",
 "Deduplicate to distinct user-day first. Then number each user's days with ROW_NUMBER() ordered by date. The date minus the row number is constant within a run of consecutive days, so grouping by user and that constant gives each streak, and HAVING COUNT(*) >= 3 keeps the qualifying ones. The longest streak is the maximum count per user. Self-joins work for a fixed length of 3 but break when the length changes. I'd also confirm how 'day' is defined, since time zones can split or merge a late-night session.",
 ["window-functions","retention-cohorts","sql-fundamentals"],["streak"],"implementation"),
Q("sql-013","You join orders to order_items to compute revenue, then add a join to payments. Total revenue suddenly doubles. What happened, and how do you prevent it?","SQL","medium",C,"Mid-level DS interview, analytics-heavy company",
 [("How would you check for this before trusting a new join?","test validation habits such as row counts and key uniqueness"),
  ("Show a fix when you need both item-level and payment-level figures.","test pre-aggregating before joining"),
  ("Does the same problem appear with a LEFT JOIN?","test understanding that join type does not prevent duplication")],
 "A join multiplies rows whenever the key is not unique on both sides, so sums taken after the join silently inflate.",
 "There are probably duplicates in the data, so I'd add DISTINCT.",
 "Payments are one-to-many per order (split payments, retries), so each order row is repeated once per payment before the SUM runs. DISTINCT only hides it when rows are identical and can delete legitimate duplicates. The fix is to aggregate each table to one row per order before joining, or to compute each measure in its own CTE and join the results on order_id. To prevent it, I check row counts and key uniqueness before and after every join (COUNT(*) versus COUNT(DISTINCT order_id)) and reconcile totals against the source table. A LEFT JOIN does not help, because the duplication comes from matches, not from unmatched rows.",
 ["joins","debugging","data-quality"],["join"],"case"),
Q("sql-014","What's the difference between COUNT(*), COUNT(column) and COUNT(DISTINCT column)? When do they give different answers?","SQL","easy",C,"Phone screen, SQL fundamentals",
 [("A column has 100 rows, 20 NULLs and 30 distinct non-null values. What do the three return?","test applying the rules to concrete numbers"),
  ("How do NULLs affect AVG and SUM?","test NULL semantics in other aggregates"),
  ("Does COUNT(DISTINCT) have a cost at scale?","test awareness of performance")],
 "COUNT(*) counts rows and COUNT(column) counts non-NULL values. The gap between them is a data-quality signal in its own right.",
 "COUNT(*) counts everything and COUNT(DISTINCT) counts unique values.",
 "COUNT(*) counts rows regardless of content, COUNT(col) counts rows where col is not NULL, and COUNT(DISTINCT col) counts distinct non-NULL values. With 100 rows, 20 NULLs and 30 distinct values, that is 100, 80 and 30. AVG and SUM skip NULLs, so AVG(col) divides by 80, not 100, which is why a NULL-heavy column can shift an average. COUNT(DISTINCT) is expensive on large tables because it has to deduplicate, so at scale I'd consider an approximate distinct count when exactness is not required. Comparing COUNT(*) with COUNT(col) is also a quick completeness check.",
 ["null-semantics","sql-fundamentals"],["aggregate-function","null-value"],"concept"),
Q("sql-015","Compute the median order value per customer segment. Your warehouse has no MEDIAN function.","SQL","hard",C,"Senior analytics interview",
 [("How does your approach behave when a segment has an even number of orders?","test the even-count definition of the median"),
  ("Why might you report the median rather than the mean here?","test choosing summary statistics"),
  ("What does this cost on a billion-row table?","test scalability thinking and approximate percentiles")],
 "A median needs an ordering within each group. The even-count case and the cost of sorting separate a working answer from a correct one.",
 "Sort the orders and pick the middle row.",
 "If PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY amount) exists I'd use it. Otherwise I'd rank rows within each segment with ROW_NUMBER() and compute the segment's row count with a window, then average the one or two middle rows (where the rank is floor((n+1)/2) or ceil((n+1)/2)). That handles even counts by averaging the two middle values. The median resists whales and skew, which suits order value. At a billion rows a full sort per segment is costly, so I'd use an approximate percentile function if exactness is not required, or sample.",
 ["summary-statistics","window-functions","sql-fundamentals"],["median","ranking"],"implementation"),
Q("sql-016","Your dashboard says the repeat purchase rate is 38%, but finance reports 31% from the same orders table. How do you reconcile them?","SQL","hard","common in senior DS interviews","Senior DS interview, stakeholder-facing role",
 [("Which definitions could legitimately differ?","test enumerating metric-definition differences"),
  ("How do you decide whose number is right?","test stakeholder alignment and metric governance"),
  ("How do you stop it happening again?","test process thinking: documented definitions and one source")],
 "Two correct queries can disagree because the metric was defined differently. The fix is agreeing on a definition, not picking a winner.",
 "One of the queries must be wrong, so I'd compare the SQL.",
 "I'd first line up the definitions: the denominator (all customers, or customers acquired in a period), the numerator window (a second purchase within 30 days versus ever), the treatment of cancelled, refunded, test and internal orders, guest checkouts, currency, and time zone cut-offs. Then I'd reproduce both numbers step by step from the same filtered base to see which step opens the gap; a few counts usually explain it. Neither is wrong until we agree what decision the metric supports. Afterwards I'd put one definition in a documented metrics layer so dashboards and finance read the same source.",
 ["retention-cohorts","data-quality","stakeholder-communication"],["repeat-purchase-rate","cohort"],"case"),
])
