from h import *
C="common in DS interviews"
write("stats", [
Q("stats-008","A coin lands heads 7 times out of 10. Is it biased?","Statistics","easy",C,"Phone screen, statistics fundamentals",
 [("What would change if it were 70 out of 100?","test how sample size affects evidence"),
  ("What is the p-value here, and what does it mean?","test correct interpretation of p-values"),
  ("What if you had decided in advance to test only for too many heads?","test one-sided versus two-sided tests")],
 "Seven out of ten is weak evidence. The same proportion in a larger sample would be strong, so evidence depends on sample size, not just the observed rate.",
 "7 out of 10 is more than 50%, so it's probably biased.",
 "Under a fair coin, 7 or more heads in 10 flips has probability about 17%, and the two-sided p-value (7 or more, or 3 or fewer) is about 0.34, so there is no evidence of bias. With 70 heads out of 100 the p-value is far below 0.001, which is strong evidence. The p-value is the probability of data this extreme if the coin is fair, not the probability that the coin is fair. I'd also report a confidence interval for the heads rate, which for 10 flips spans roughly 35% to 93%, to show how little 10 flips tell us. One-sided versus two-sided should be chosen before seeing the data.",
 ["hypothesis-testing","sampling-distributions","confidence-intervals"],["p-value","sample-size"],"concept"),
Q("stats-009","Explain the central limit theorem to a product manager. Why does it matter for A/B tests?","Statistics","easy",C,"Stakeholder-facing DS interview",
 [("When does the central limit theorem not help much?","test limits: heavy tails, small samples, strong skew"),
  ("How large does n need to be?","test avoiding a rule-of-30 answer"),
  ("What is the standard error, and how does it relate?","test linking the theorem to standard error")],
 "The theorem says averages behave predictably even when individual data does not, which is what makes ordinary test statistics usable on messy metrics.",
 "With enough samples, the data becomes normally distributed.",
 "I'd say: individual users' spending is messy and skewed, but if you repeatedly take samples and average them, those averages form a bell shape centered on the true mean, with a spread that shrinks as samples grow. That is why we can put a margin of error on an average and compare two groups with a standard test. The common misconception is that the data itself becomes normal; it is the distribution of the average. How large n must be depends on the skew: 30 is a rough rule for mild skew, but a metric dominated by rare big spenders may need thousands. With a heavy-tailed metric I'd check with a bootstrap.",
 ["sampling-distributions","explaining-concepts","ab-testing"],["central-limit-theorem","standard-error"],"concept"),
Q("stats-010","Revenue per user is heavily right-skewed. Do you report the mean or the median, and does it change how you test?","Statistics","medium",C,"Experimentation DS interview",
 [("A few big spenders account for 40% of revenue. Which metric answers the business question?","test linking the metric to the decision"),
  ("Would you still use a t-test?","test choosing a test under skew: bootstrap, Mann-Whitney, log transform"),
  ("What is Mann-Whitney actually comparing?","test knowing it is not strictly a median test")],
 "The mean answers 'how much money in total' and the median answers 'what does a typical user do'. Pick the one that matches the decision, then choose a test that compares that quantity.",
 "Use the median because the data is skewed.",
 "It depends on the decision. If we care about total revenue, the mean is the right quantity even though it is noisy, since totals are mean times users. If we care about a typical user's experience, the median or a trimmed mean is better. For testing the mean, the central limit theorem usually still rescues a t-test at large n, but with heavy tails I'd confirm with a bootstrap interval or reduce variance with CUPED or winsorizing, stating what that does to the quantity being estimated. Mann-Whitney tests whether one group tends to produce larger values, not specifically whether medians differ. I'd report both mean and median with intervals.",
 ["summary-statistics","ab-testing","missing-data-and-outliers"],["mean","median","outliers"],"case"),
Q("stats-011","A PM asks: 'What's the probability that variant B is better than A?' Your frequentist test gives p = 0.03. Can you answer them?","Statistics","medium","common in senior DS interviews","Senior DS interview, stakeholder communication",
 [("What does the p-value tell you, in plain words?","test correct interpretation"),
  ("How would you actually compute the probability the PM wants?","test Bayesian posterior and priors"),
  ("What is the weakness of that answer?","test prior sensitivity")],
 "A p-value is the chance of data like this if there were no difference, not the chance that B is better. The PM's question needs a posterior.",
 "p = 0.03 means there is a 97% chance that B is better.",
 "No. p = 0.03 means that if A and B truly performed the same, data this extreme would show up about 3% of the time. It is not the probability that B is better. To answer the PM's actual question I'd fit a Bayesian model: put priors on each conversion rate (often weakly informative Beta priors), update with the data, and report P(B > A) from the posterior along with the expected lift and the expected loss if we choose wrong. The answer depends on the prior, which should be stated and tested for sensitivity. With lots of data and weak priors the two approaches usually agree closely. I'd frame it for the PM in terms of decision risk.",
 ["bayesian-inference","hypothesis-testing","stakeholder-communication"],["p-value","frequentist"],"concept"),
Q("stats-012","You check an A/B test dashboard every day and stop as soon as p < 0.05. What's wrong with that?","Statistics","medium",C,"Experimentation DS interview",
 [("Roughly how much does the false-positive rate inflate?","test intuition about repeated looks"),
  ("How would you design the test so early stopping is allowed?","test sequential methods and alpha spending"),
  ("What if you have to decide on interim data anyway?","test practical governance")],
 "Every extra look is another chance for noise to cross the threshold, so a 5% test checked daily rejects far more than 5% of true nulls.",
 "You should wait until the test is over.",
 "A fixed-horizon p-value is only valid if you look once, at the pre-planned sample size. Stopping when it first dips below 0.05 exploits random fluctuation: with daily looks over a few weeks, the real false-positive rate can reach 20 to 30%. Options: pre-commit to a sample size and read results once; or use a sequential design such as group-sequential or alpha-spending boundaries, always-valid p-values, or a Bayesian stopping rule with calibrated thresholds. If stakeholders need early reads, I'd allow monitoring for harm on guardrail metrics but not for declaring wins. Novelty effects and day-of-week cycles are another reason to run full weeks.",
 ["ab-testing","hypothesis-testing","multiple-testing","bayesian-inference"],["p-value","type-i-error"],"case"),
Q("stats-013","Marketing says customers who got a discount retained 20% better, so discounts work. You can't run an experiment. How do you estimate whether the discount caused it?","Statistics","hard","common in senior DS interviews","Senior DS interview, causal reasoning",
 [("Why might discounted customers have retained better anyway?","test selection bias reasoning"),
  ("What observational methods would you consider?","test matching, regression adjustment, difference-in-differences, instruments"),
  ("What would make you say the estimate is still not credible?","test sensitivity analysis and humility")],
 "Customers who got discounts were not chosen at random, so the raw comparison mixes the discount's effect with who was selected.",
 "Control for other variables like age and spend in a regression.",
 "First I'd learn how discounts were assigned: if marketing targeted engaged customers, or at-risk customers, the groups differ before treatment. I'd map the likely causal structure, then compare like with like: propensity-score matching or weighting, or regression adjustment on pre-treatment covariates only. If there is a rollout date, a region or an eligibility cutoff, difference-in-differences or regression discontinuity gives a stronger estimate. I'd check covariate balance and run a sensitivity analysis for unmeasured factors. Adjustment only handles what we measured, so I'd say so and recommend a small holdout experiment going forward.",
 ["causal-inference","segment-analysis","tradeoffs"],["causation","control-group","retention"],"case"),
Q("stats-014","Your A/B test has 100,000 users per arm and a 2% click rate. How do you compute a confidence interval for the difference in click rates?","Statistics","medium",C,"Experimentation DS interview",
 [("What are the assumptions behind that formula?","test independence and the normal approximation"),
  ("What if randomization was by user but you count clicks per session?","test the unit of analysis"),
  ("How would you check the result without a formula?","test bootstrap or simulation")],
 "The unit you randomize on must be the unit you analyze. Otherwise the standard error is too small.",
 "Compare 2% to the other arm's rate and see which is larger.",
 "With p1 and p2 as the arm rates, the standard error of the difference is sqrt(p1(1-p1)/n1 + p2(1-p2)/n2), and the 95% interval is the difference plus or minus 1.96 times that. For about 2% and 100,000 users per arm the standard error is roughly 0.063 percentage points, so differences under about 0.12 points are inside the noise. The formula assumes independent users and a large enough n for the normal approximation, both fine here. A common error is analyzing clicks or sessions while randomizing users, which understates variance; I'd analyze per user or use cluster-robust errors. A bootstrap is a good cross-check.",
 ["confidence-intervals","sampling-distributions","ab-testing"],["standard-error","confidence-interval"],"implementation"),
Q("stats-015","Users in your experiment interact with each other, as in a marketplace or a social feature. Does a standard A/B test still work?","Statistics","hard","common in senior DS interviews","Senior DS interview at a marketplace or social company",
 [("What would the bias look like in a two-sided marketplace?","test reasoning about spillover direction"),
  ("What design alternatives exist?","test cluster, switchback and geo experiments"),
  ("How would you know the effect is leaking between groups?","test diagnostics")],
 "A standard test assumes one user's outcome does not depend on others' assignments. When users interact, control is contaminated and the measured lift is biased.",
 "Yes, just randomize users into two groups.",
 "It can mislead. A/B tests assume one user's outcome doesn't depend on anyone else's assignment. In a marketplace, treated buyers who grab limited inventory take it from control buyers, so the measured lift overstates what launching to everyone would deliver. In social products, treated users influence their control friends, which shrinks the measured effect. Better designs randomize at the level where the interaction happens: clusters of connected users, geographies or time-based switchbacks, accepting lower power. I'd compare cluster-level and user-level estimates as a diagnostic and consider modelling the equilibrium effect.",
 ["ab-testing","causal-inference","edge-cases"],["control-group","ab-test"],"case"),
])
