from h import *
import h
def _tag(i, l): TAGS[i] = {"label": l, "kind": "subject"}
for i, l in [("linear-models","Linear & regularized models"),("decision-trees","Decision trees & forests"),("svm","Support vector machines"),("knn","k-nearest neighbors"),
 ("probabilistic-models","Probabilistic models"),("anomaly-detection","Anomaly detection"),("clustering","Clustering"),("dimensionality-reduction","Dimensionality reduction"),
 ("feature-selection","Feature selection"),("ensembling","Ensembling & stacking"),("hyperparameter-tuning","Hyperparameter tuning"),("optimization","Gradient descent & optimizers"),
 ("loss-functions","Loss functions"),("neural-networks","Neural networks"),("sequence-models","Sequence models & attention"),("transfer-learning","Transfer learning"),
 ("text-features","Text representations"),("llm-training","How LLMs are trained"),("maximum-likelihood","Maximum likelihood"),("categorical-tests","Chi-square & ANOVA"),
 ("bandits","Bandits & adaptive tests"),("survival-analysis","Survival analysis"),("forecasting-models","Classical forecasting models"),("forecast-metrics","Forecast accuracy metrics"),
 ("recommender-systems","Recommender systems"),("feature-scaling","Feature scaling")]: _tag(i, l)
def T(id, label, d, tag): TERMS[id] = {"label": label, "definition": d, "tag": tag}
T("linear-regression","Linear regression","A model that predicts a number as a weighted sum of input features.","linear-models")
T("ridge","Ridge regression","Linear regression with a penalty on the squared size of its coefficients (an L2 penalty).","linear-models")
T("lasso","Lasso","Linear regression with a penalty on the absolute size of its coefficients (an L1 penalty).","linear-models")
T("decision-tree","Decision tree","A model that makes predictions by asking a sequence of yes-or-no questions about the features.","decision-trees")
T("lightgbm","LightGBM","A gradient boosting library from Microsoft.","gradient-boosting")
T("catboost","CatBoost","A gradient boosting library from Yandex.","gradient-boosting")
T("support-vector-machine","Support vector machine","A classifier that separates classes with a boundary chosen using the points closest to it.","svm")
T("support-vector-regression","SVR","Support vector regression: the regression counterpart of the support vector machine.","svm")
T("k-nearest-neighbors","k-nearest neighbors","A method that predicts using the labels of the k most similar training examples.","knn")
T("naive-bayes","Naive Bayes","A family of simple probabilistic classifiers based on Bayes' rule.","probabilistic-models")
T("generalized-linear-model","Generalized linear model","A family of models that extends linear regression to outcomes with other distributions, such as counts or yes/no.","probabilistic-models")
T("isolation-forest","Isolation forest","An unsupervised method for scoring how unusual each observation is, built from random trees.","anomaly-detection")
T("k-means","k-means","A clustering method that groups points around k center points.","clustering")
T("clustering","Clustering","Grouping similar items together without predefined labels.","clustering")
T("dbscan","DBSCAN","A clustering method that groups points by how densely packed they are.","clustering")
T("hierarchical-clustering","Hierarchical clustering","A clustering method that builds a tree of nested groups.","clustering")
T("gaussian-mixture-model","Gaussian mixture model","A model that describes data as a blend of several bell-shaped distributions.","clustering")
T("pca","PCA","Principal component analysis: a technique that rewrites data in terms of new, uncorrelated directions.","dimensionality-reduction")
T("t-sne","t-SNE","A technique for drawing high-dimensional data as a two-dimensional picture.","dimensionality-reduction")
T("feature-selection","Feature selection","Choosing a subset of the available input features to use in a model.","feature-selection")
T("stacking","Stacking","An ensemble method in which a second model learns to combine the predictions of several base models.","ensembling")
T("smote","SMOTE","Synthetic Minority Over-sampling Technique: a way of creating artificial examples of a rare class.","class-imbalance")
T("hyperparameter","Hyperparameter","A setting chosen before training, such as tree depth, rather than learned from the data.","hyperparameter-tuning")
T("neural-network","Neural network","A model made of layers of simple units whose connection weights are learned from data.","neural-networks")
T("backpropagation","Backpropagation","The procedure used to compute how each weight in a neural network should change.","neural-networks")
T("gradient-descent","Gradient descent","An optimization method that repeatedly adjusts parameters in the direction that lowers the loss.","optimization")
T("learning-rate","Learning rate","The size of each update step taken while training a model.","optimization")
T("loss-function","Loss function","A formula that scores how wrong a model's predictions are, which training tries to minimize.","loss-functions")
T("dropout","Dropout","A neural network technique in which random units are switched off during training.","neural-networks")
T("batch-normalization","Batch normalization","A neural network layer that standardizes its inputs across each training batch.","neural-networks")
T("convolutional-neural-network","Convolutional neural network","A neural network that scans small filters across grid-like data such as images.","neural-networks")
T("rnn","RNN","Recurrent neural network: a model that reads a sequence one step at a time, carrying a memory forward.","sequence-models")
T("transformer","Transformer","A neural network architecture built around attention, used by most modern language models.","sequence-models")
T("attention","Attention","A mechanism that lets a model weigh how relevant each part of its input is when producing an output.","sequence-models")
T("pretrained-model","Pretrained model","A model already trained on a large dataset, available as a starting point.","transfer-learning")
T("tf-idf","TF-IDF","Term frequency-inverse document frequency: a score for how characteristic a word is of a document.","text-features")
T("word2vec","word2vec","A method for learning a vector of numbers for each word from large amounts of text.","text-features")
T("rlhf","RLHF","Reinforcement learning from human feedback: training a model using human preferences as a signal.","llm-training")
T("likelihood","Likelihood","The probability a model assigns to the observed data, viewed as a function of the model's parameters.","maximum-likelihood")
T("chi-square-test","Chi-square test","A hypothesis test comparing observed counts in categories with the counts expected under no relationship.","categorical-tests")
T("multi-armed-bandit","Multi-armed bandit","A method that adaptively allocates traffic among options while learning which performs best.","bandits")
T("arima","ARIMA","AutoRegressive Integrated Moving Average: a classical model for forecasting a single time series.","forecasting-models")
T("exponential-smoothing","Exponential smoothing","A forecasting method that weights recent observations more heavily than older ones.","forecasting-models")
T("prophet","Prophet","An open-source forecasting library from Meta.","forecasting-models")
T("mape","MAPE","Mean absolute percentage error: the average of absolute errors as a percentage of the actual values.","forecast-metrics")
T("matrix-factorization","Matrix factorization","A technique that approximates a large table as the product of two smaller ones.","recommender-systems")
T("feature-scaling","Feature scaling","Rewriting features so they sit on comparable ranges.","feature-scaling")
T("cosine-similarity","Cosine similarity","A measure of how alike two vectors are, based on the angle between them.","text-features")
T("lora","LoRA","Low-Rank Adaptation: a technique for fine-tuning a model by training small added matrices.","prompting-vs-fine-tuning")
